//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHINHANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHINHANH()
        {
            this.LOTRINHs = new HashSet<LOTRINH>();
            this.DM_PHONGBAN = new HashSet<DM_PHONGBAN>();
            this.DM_PHONGBAN1 = new HashSet<DM_PHONGBAN>();
            this.DM_PHONGBAN2 = new HashSet<DM_PHONGBAN>();
        }
    
        public string maCN { get; set; }
        public string tenCN { get; set; }
        public string SDT_CN { get; set; }
        public string DC_CN { get; set; }
        public string MST { get; set; }
        public string soFAX_CN { get; set; }
        public short tuychonin { get; set; }
        public string maCTY { get; set; }
    
        public virtual CONGTY CONGTY { get; set; }
        public virtual CONGTY CONGTY1 { get; set; }
        public virtual CONGTY CONGTY2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINH> LOTRINHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_PHONGBAN> DM_PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_PHONGBAN> DM_PHONGBAN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_PHONGBAN> DM_PHONGBAN2 { get; set; }
    }
}
