//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HD
    {
        public decimal ID_chitiet_HD { get; set; }
        public Nullable<decimal> ID_HD { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public Nullable<int> STT { get; set; }
        public string DIENGIAI { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> M3BVMT { get; set; }
        public Nullable<decimal> GIABVMT { get; set; }
        public Nullable<decimal> USER_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public Nullable<decimal> USER_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public Nullable<int> isImport { get; set; }
        public Nullable<decimal> chitietTDC_id { get; set; }
    
        public virtual TDC_CHITIETHD TDC_CHITIETHD { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
