//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungTuLog
    {
        public decimal id { get; set; }
        public Nullable<decimal> id_ct { get; set; }
        public Nullable<decimal> id_hd { get; set; }
        public string manv { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public string lydo { get; set; }
        public Nullable<int> nvid { get; set; }
        public Nullable<System.DateTime> ngaythu { get; set; }
        public Nullable<decimal> IDKH { get; set; }
    }
}
