//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGTU_HOADON
    {
        public decimal ID_CT { get; set; }
        public decimal ID_HD { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<bool> DADONGBO { get; set; }
        public Nullable<decimal> NVID_THU { get; set; }
        public Nullable<decimal> NVID_CREATE { get; set; }
        public string NVID_Dongbo { get; set; }
        public Nullable<System.DateTime> NGAYTHU { get; set; }
        public Nullable<System.DateTime> NGAYDONGBO { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public string DANHBO { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public string ID_Kyghi { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<bool> isdachuyen { get; set; }
        public Nullable<bool> isdadongbo { get; set; }
        public Nullable<decimal> GIAODICHID { get; set; }
        public string GHICHU { get; set; }
        public string LOG_THUHO { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
