//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGTU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUNGTU()
        {
            this.GACHNOCKs = new HashSet<GACHNOCK>();
            this.GACHNOKHs = new HashSet<GACHNOKH>();
            this.GACHNONVs = new HashSet<GACHNONV>();
        }
    
        public decimal ID_CT { get; set; }
        public string SOCT { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string MALOAI { get; set; }
        public Nullable<decimal> NV_ID_LAP { get; set; }
        public Nullable<decimal> NAM_ID { get; set; }
        public string ID_KYGHI { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public Nullable<decimal> NV_ID_NOP { get; set; }
        public Nullable<System.DateTime> NGAYCT { get; set; }
        public string GHICHU { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<bool> danop { get; set; }
        public string ghichuketoan { get; set; }
        public Nullable<int> user_confirm { get; set; }
        public Nullable<System.DateTime> date_confirm { get; set; }
        public Nullable<decimal> USER_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
    
        public virtual DM_LOAICHUNGTU DM_LOAICHUNGTU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GACHNOCK> GACHNOCKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GACHNOKH> GACHNOKHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GACHNONV> GACHNONVs { get; set; }
    }
}
