//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public decimal ID_KH { get; set; }
        public string madanhbo { get; set; }
        public string hoten_KH { get; set; }
        public string diachi { get; set; }
        public string SDT_KH { get; set; }
        public string MST_KH { get; set; }
        public string email { get; set; }
        public string NganhNghe { get; set; }
        public long MA_HTTT { get; set; }
        public Nullable<int> MA_NN { get; set; }
        public int soNK { get; set; }
        public string soHK { get; set; }
        public string ma_giabvmt { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string nguoitao { get; set; }
        public Nullable<long> maDH { get; set; }
        public string soseri_DH { get; set; }
        public int trangthai { get; set; }
        public Nullable<System.DateTime> ngaylapdat { get; set; }
        public Nullable<System.DateTime> ngaydoi_DH { get; set; }
        public Nullable<long> MAKC { get; set; }
        public Nullable<System.DateTime> Ngay_Kiemdinh { get; set; }
        public string nguoilapdat { get; set; }
        public string maphuong { get; set; }
        public Nullable<decimal> idKV { get; set; }
        public Nullable<decimal> idduong { get; set; }
        public string sonha { get; set; }
        public string diachithanhtoan { get; set; }
        public bool thanhtoankhaclapdat { get; set; }
        public string maLT { get; set; }
        public int stt_ghi { get; set; }
        public int stt_thu { get; set; }
        public string sohopdong { get; set; }
        public Nullable<System.DateTime> ngaytrangthai { get; set; }
        public string ghichu { get; set; }
        public string maDT { get; set; }
        public Nullable<bool> ischuaxacdinh_NK { get; set; }
        public string bankaccountName { get; set; }
        public string BankName { get; set; }
        public string Banknumber { get; set; }
        public string contactperson { get; set; }
        public string RepresentPerson { get; set; }
        public Nullable<int> STT_ghi_old { get; set; }
        public Nullable<int> STT_thu_old { get; set; }
        public Nullable<bool> isDongBo { get; set; }
        public string KichCo { get; set; }
        public string tenhieu { get; set; }
        public string ViTri_LD { get; set; }
        public Nullable<decimal> giaphi { get; set; }
        public string tenDT { get; set; }
        public string tenHTTT { get; set; }
        public string tenLT { get; set; }
        public string Ten_NN { get; set; }
        public string BCT { get; set; }
    }
}
