//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DOITUONGSUDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_DOITUONGSUDUNG()
        {
            this.DM_BANGGIA = new HashSet<DM_BANGGIA>();
        }
    
        public string maDT { get; set; }
        public string tenDT { get; set; }
        public string ma_giaBVMT { get; set; }
        public Nullable<bool> theoNK { get; set; }
        public Nullable<int> stt { get; set; }
        public string MaLoaiHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_BANGGIA> DM_BANGGIA { get; set; }
    }
}
