//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GHICHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_GHICHU()
        {
            this.CHISONUOCs = new HashSet<CHISONUOC>();
        }
    
        public int ghichuid { get; set; }
        public string noidung { get; set; }
        public string maloai_yc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHISONUOC> CHISONUOCs { get; set; }
        public virtual DM_LOAIYEUCAU DM_LOAIYEUCAU { get; set; }
    }
}
