//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAICHUNGTU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_LOAICHUNGTU()
        {
            this.CHUNGTUs = new HashSet<CHUNGTU>();
        }
    
        public string maloai { get; set; }
        public string tenloai { get; set; }
        public Nullable<int> taikhoan_co { get; set; }
        public Nullable<int> taikhoan_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUNGTU> CHUNGTUs { get; set; }
    }
}
