//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHONGBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_PHONGBAN()
        {
            this.DM_TO = new HashSet<DM_TO>();
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public string maPB { get; set; }
        public string tenPB { get; set; }
        public string mota { get; set; }
        public string maCN { get; set; }
    
        public virtual CHINHANH CHINHANH { get; set; }
        public virtual CHINHANH CHINHANH1 { get; set; }
        public virtual CHINHANH CHINHANH2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_TO> DM_TO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
