//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCSO
    {
        public string IDKH { get; set; }
        public int NAM { get; set; }
        public int THANG { get; set; }
        public string MADP { get; set; }
        public string SODB { get; set; }
        public string MALT { get; set; }
        public string DOT { get; set; }
        public string TENKH { get; set; }
        public Nullable<int> CHISODAU { get; set; }
        public Nullable<int> CHISOCUOI { get; set; }
        public Nullable<int> KLTIEUTHU { get; set; }
        public Nullable<int> TBTT { get; set; }
        public string CODE { get; set; }
        public Nullable<bool> ISGCS { get; set; }
        public Nullable<System.DateTime> NGAYGHI { get; set; }
        public Nullable<System.DateTime> NGAYGHI_TT { get; set; }
        public Nullable<int> CHISODAU_T1 { get; set; }
        public Nullable<int> CHISOCUOI_T1 { get; set; }
        public Nullable<int> KLTIEUTHU_T1 { get; set; }
        public string CODE_T1 { get; set; }
        public Nullable<int> CHISODAU_T2 { get; set; }
        public Nullable<int> CHISOCUOI_T2 { get; set; }
        public Nullable<int> KLTIEUTHU_T2 { get; set; }
        public string CODE_T2 { get; set; }
        public Nullable<int> CHISODAU_T3 { get; set; }
        public Nullable<int> CHISOCUOI_T3 { get; set; }
        public Nullable<int> KLTIEUTHU_T3 { get; set; }
        public string CODE_T3 { get; set; }
        public Nullable<int> CSTDH { get; set; }
        public Nullable<int> CSLDH { get; set; }
        public Nullable<System.DateTime> NGAYTDH { get; set; }
        public Nullable<System.DateTime> NGAYLDH { get; set; }
        public Nullable<int> STT { get; set; }
        public string MAMDSD { get; set; }
        public Nullable<int> DINHMUC { get; set; }
        public string SONHA { get; set; }
        public string TENDUONG { get; set; }
        public string SONHAMOI { get; set; }
        public string TENDUONGMOI { get; set; }
        public string MADH { get; set; }
        public string MALDH { get; set; }
        public Nullable<int> KICHCO { get; set; }
        public Nullable<int> VITRI { get; set; }
        public string SDT { get; set; }
        public string GHICHU { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public Nullable<System.DateTime> NGAYGUI { get; set; }
        public string SERIALNUMBER { get; set; }
        public string GHICHUMH { get; set; }
        public Nullable<System.DateTime> NGAYGUICS { get; set; }
        public Nullable<bool> ISIMAGE { get; set; }
    }
}
