//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSBIENNHANH_APP
    {
        public Nullable<long> STT { get; set; }
        public decimal tongtien { get; set; }
        public int soluong { get; set; }
        public string SOCT { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public int NV_ID_nop { get; set; }
        public string trangthai { get; set; }
        public string quyenso { get; set; }
        public decimal ID_CT { get; set; }
        public string ID_kyghi { get; set; }
        public int soluongchuagach { get; set; }
        public string nvnop { get; set; }
        public int NV_ID_lap { get; set; }
        public string nvlap { get; set; }
        public string maloai { get; set; }
        public Nullable<decimal> tongtienapp { get; set; }
        public int Active { get; set; }
    }
}
