//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCHUNGTU_APP_INVOICE
    {
        public Nullable<decimal> tongtienHD { get; set; }
        public Nullable<decimal> tongtienapp { get; set; }
        public decimal ID_CT { get; set; }
        public string SOCT { get; set; }
        public string NVLap { get; set; }
        public string NVNop { get; set; }
        public string ten_kyghi { get; set; }
        public Nullable<System.DateTime> ngayct { get; set; }
        public Nullable<int> slhoadon { get; set; }
    }
}
