//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSGACHNO
    {
        public int trangthai { get; set; }
        public decimal id_hd { get; set; }
        public Nullable<decimal> NV_ID_NOP { get; set; }
        public Nullable<int> NV_ID { get; set; }
    }
}
