//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSHD_PhieuThu
    {
        public decimal ID_HD { get; set; }
        public string SO_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string ten_kyghi { get; set; }
        public Nullable<int> nam { get; set; }
        public string kyghi { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public string MaLT { get; set; }
        public string DANHBO { get; set; }
        public string hoten { get; set; }
        public decimal NV_ID { get; set; }
        public string checks { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public Nullable<System.DateTime> ngay_thu_tien { get; set; }
        public string diachi { get; set; }
        public string sonha { get; set; }
        public string tenPhuong { get; set; }
        public string tenQuan { get; set; }
    }
}
