//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSPHIEUTHU_APP
    {
        public string hoten_KH { get; set; }
        public string madanhbo { get; set; }
        public string diachi { get; set; }
        public Nullable<decimal> thanhtien_app { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<int> luongtieuthu { get; set; }
        public Nullable<System.DateTime> ngayghi { get; set; }
        public string SO_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string NVNop { get; set; }
        public string SOCT { get; set; }
        public string trangthai { get; set; }
        public string tenLT { get; set; }
        public string maLT { get; set; }
        public string NVGhi { get; set; }
        public decimal ID_KH { get; set; }
        public string ID_kyghi { get; set; }
        public string dongbo { get; set; }
        public Nullable<bool> dadongbo { get; set; }
        public decimal id_chisonuoc { get; set; }
    }
}
