//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GACHNO_LOG
    {
        public decimal LOG_ID { get; set; }
        public Nullable<decimal> GACHNO_ID { get; set; }
        public Nullable<decimal> ID_CT { get; set; }
        public Nullable<decimal> ID_HD { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public string SOCT { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<decimal> USER_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN_OLD { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN_MOI { get; set; }
        public Nullable<decimal> NV_ID_NOP_OLD { get; set; }
        public string ID_KYGHI_OLD { get; set; }
        public string ID_KYGHI_MOI { get; set; }
    }
}
