//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GACHNONV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GACHNONV()
        {
            this.DANGNGANs = new HashSet<DANGNGAN>();
        }
    
        public decimal GachnoNVID { get; set; }
        public Nullable<decimal> IDHD { get; set; }
        public Nullable<decimal> IDKH { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<System.DateTime> Ngaythanhtoan { get; set; }
        public Nullable<int> NVID { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<decimal> IDCT { get; set; }
        public Nullable<int> NVID_Nop { get; set; }
    
        public virtual CHUNGTU CHUNGTU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGAN> DANGNGANs { get; set; }
    }
}
