//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAODICH
    {
        public decimal GIAODICH_ID { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public string DANHBO { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> TRANHTHAI { get; set; }
        public string LYDO { get; set; }
        public Nullable<int> USERID_CREATE { get; set; }
        public Nullable<int> USERID_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
    }
}
