//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
            this.CHUNGTU_HOADON = new HashSet<CHUNGTU_HOADON>();
            this.DANGNGANs = new HashSet<DANGNGAN>();
            this.GACHNOes = new HashSet<GACHNO>();
        }
    
        public decimal ID_HD { get; set; }
        public Nullable<decimal> keys { get; set; }
        public string kyghi { get; set; }
        public Nullable<int> nam { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public string MST { get; set; }
        public string MADT { get; set; }
        public Nullable<int> soNK { get; set; }
        public Nullable<long> ma_HTTT { get; set; }
        public string MaLT { get; set; }
        public string hoten { get; set; }
        public Nullable<bool> IsInHD { get; set; }
        public string sohopdong { get; set; }
        public Nullable<int> DMKH { get; set; }
        public string MTT { get; set; }
        public string MGB { get; set; }
        public string DANHBO { get; set; }
        public string SOPHATHANH { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public Nullable<int> CSMoi { get; set; }
        public Nullable<int> CSCu { get; set; }
        public Nullable<int> m3tieuthu { get; set; }
        public Nullable<int> m3BVMT { get; set; }
        public Nullable<decimal> dongiaBVMT { get; set; }
        public Nullable<decimal> tienBVMT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> tienvat { get; set; }
        public Nullable<decimal> tongtien0VAT { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public string MAU_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string SO_HD { get; set; }
        public Nullable<System.DateTime> ArisingDate { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<bool> gachno { get; set; }
        public Nullable<bool> isKhoDoi { get; set; }
        public Nullable<decimal> trangthai_id { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public Nullable<decimal> user_create { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<decimal> user_update { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public Nullable<decimal> LoaiHD_ID { get; set; }
        public Nullable<int> ischeck { get; set; }
        public Nullable<decimal> hoadonTDC_id { get; set; }
        public string cuonGCS { get; set; }
        public Nullable<int> STT_thu { get; set; }
        public string diachihoadon { get; set; }
        public Nullable<System.DateTime> ngaychuyenno { get; set; }
        public Nullable<bool> isDangNgan { get; set; }
        public Nullable<bool> isingiaybao { get; set; }
        public Nullable<bool> isdongbo { get; set; }
        public Nullable<decimal> tienuoc_dc { get; set; }
        public Nullable<decimal> tienthue_dc { get; set; }
        public Nullable<decimal> tienphi_dc { get; set; }
        public string diachilapdat { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> iskhoanuoc { get; set; }
        public Nullable<System.DateTime> ngaykhoanuoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUNGTU_HOADON> CHUNGTU_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGAN> DANGNGANs { get; set; }
        public virtual DM_DOT DM_DOT { get; set; }
        public virtual DM_KYGHI DM_KYGHI { get; set; }
        public virtual DM_KYGHI DM_KYGHI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GACHNO> GACHNOes { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
        public virtual TDC_HOADON TDC_HOADON { get; set; }
    }
}
