//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG_TDC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG_TDC()
        {
            this.TIEUTHUs = new HashSet<TIEUTHU>();
        }
    
        public string IDKH { get; set; }
        public string IDKHCU { get; set; }
        public decimal MADP { get; set; }
        public string SODB { get; set; }
        public string MALT { get; set; }
        public string MAY { get; set; }
        public string TO { get; set; }
        public string DOT { get; set; }
        public string MADB { get; set; }
        public int STT { get; set; }
        public string MALKH { get; set; }
        public string MAMDSD { get; set; }
        public string MABG { get; set; }
        public decimal MAKV { get; set; }
        public string TENKH { get; set; }
        public string SONHA { get; set; }
        public string TENDUONG { get; set; }
        public string DIACHITT { get; set; }
        public string MAQUAN { get; set; }
        public string MAPHUONG { get; set; }
        public string MAKHOI { get; set; }
        public string MADPLD { get; set; }
        public string SDT { get; set; }
        public string SOHD { get; set; }
        public System.DateTime NGAYHD { get; set; }
        public string CMND { get; set; }
        public System.DateTime NGAYCAP { get; set; }
        public string MADDK { get; set; }
        public string EMAIL { get; set; }
        public string STK { get; set; }
        public string MST { get; set; }
        public long MAHTTT { get; set; }
        public int SOHO { get; set; }
        public bool ISDINHMUC { get; set; }
        public int DINHMUC { get; set; }
        public int SH { get; set; }
        public int SX { get; set; }
        public int DV { get; set; }
        public int HC { get; set; }
        public string MALDH { get; set; }
        public int THUYLK { get; set; }
        public string MADH { get; set; }
        public System.DateTime NGAYKD { get; set; }
        public string GIENG { get; set; }
        public string VAN { get; set; }
        public string CHITHAN { get; set; }
        public string CHICO { get; set; }
        public string VITRI { get; set; }
        public string CAPDO { get; set; }
        public string CONGDUNG { get; set; }
        public bool GANMOI { get; set; }
        public bool TTBAOTHAY { get; set; }
        public string DMAID { get; set; }
        public System.DateTime NGAYHT { get; set; }
        public System.DateTime NGAYTHAYDH { get; set; }
        public System.DateTime NGAYCUP { get; set; }
        public int SLANTHAYDH { get; set; }
        public string TTSD { get; set; }
        public string LOAICUP { get; set; }
        public bool KOPHIMT { get; set; }
        public System.DateTime NGAYGNHAP { get; set; }
        public bool DOITT_INHOADON { get; set; }
        public string TENKH_INHOADON { get; set; }
        public string DIACHI_INHOADON { get; set; }
        public bool ISHUY { get; set; }
        public System.DateTime NGAYHUY { get; set; }
        public System.DateTime KYHUY { get; set; }
        public System.DateTime KYAPDUNG { get; set; }
        public bool DOIDB { get; set; }
        public System.DateTime NGAYHETHANDH { get; set; }
        public string MANH { get; set; }
        public string DAIDIEN { get; set; }
        public string CHUCVU { get; set; }
        public string FAX { get; set; }
        public int CHISODAU { get; set; }
        public int CHISOCUOI { get; set; }
        public string MACQTT { get; set; }
        public bool VDH { get; set; }
        public string TENPHUONG { get; set; }
        public string TENQUAN { get; set; }
        public bool DACNPHUONG { get; set; }
        public bool ISSAPNHAP { get; set; }
        public bool HIEULUC { get; set; }
        public string GHICHU { get; set; }
        public string SONHAMOI { get; set; }
        public System.DateTime NGAYGANCU { get; set; }
    
        public virtual DM_HINHTHUCTHANHTOAN DM_HINHTHUCTHANHTOAN { get; set; }
        public virtual DM_KHUVUC DM_KHUVUC { get; set; }
        public virtual DM_PHUONG DM_PHUONG { get; set; }
        public virtual DM_QUAN DM_QUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIEUTHU> TIEUTHUs { get; set; }
    }
}
