//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_THUTIENNUOC
    {
        public decimal LOGTHU_ID { get; set; }
        public string Ky_Hieu_HD { get; set; }
        public string SO_HD { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public Nullable<decimal> NV_ID { get; set; }
        public int GIAYBAO { get; set; }
        public System.DateTime NGAYIN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
