//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_USER
    {
        public decimal id { get; set; }
        public Nullable<decimal> nguoidung_id { get; set; }
        public Nullable<System.DateTime> ngay_sd { get; set; }
        public string ghichu { get; set; }
    }
}
