//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTRINH()
        {
            this.LOTRINH_GHI = new HashSet<LOTRINH_GHI>();
            this.LOTRINH_THU = new HashSet<LOTRINH_THU>();
        }
    
        public string MaLT { get; set; }
        public string TenLT { get; set; }
        public Nullable<int> STT { get; set; }
        public string maCN { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> Date_create { get; set; }
        public Nullable<decimal> User_create { get; set; }
    
        public virtual CHINHANH CHINHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINH_GHI> LOTRINH_GHI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINH_THU> LOTRINH_THU { get; set; }
    }
}
