//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
            this.CHITIET_HD1 = new HashSet<CHITIET_HD>();
            this.DANGNGANs = new HashSet<DANGNGAN>();
            this.DANGNGANs1 = new HashSet<DANGNGAN>();
            this.DANGNGANCKs = new HashSet<DANGNGANCK>();
            this.DANGNGANCKs1 = new HashSet<DANGNGANCK>();
            this.DANGNGANKHs = new HashSet<DANGNGANKH>();
            this.DANGNGANKHs1 = new HashSet<DANGNGANKH>();
            this.DM_KYGHI = new HashSet<DM_KYGHI>();
            this.HOADONs = new HashSet<HOADON>();
            this.HOADONs1 = new HashSet<HOADON>();
            this.LOG_THUTIENNUOC = new HashSet<LOG_THUTIENNUOC>();
            this.LOTRINHs = new HashSet<LOTRINH>();
            this.LOTRINH_GHI = new HashSet<LOTRINH_GHI>();
            this.LOTRINH_THU = new HashSet<LOTRINH_THU>();
            this.MAU_HD = new HashSet<MAU_HD>();
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
            this.NHANVIEN_HOADON = new HashSet<NHANVIEN_HOADON>();
            this.NHANVIEN_HOADON1 = new HashSet<NHANVIEN_HOADON>();
            this.NHANVIEN_HOADON2 = new HashSet<NHANVIEN_HOADON>();
            this.NHANVIEN_LNV = new HashSet<NHANVIEN_LNV>();
        }
    
        public decimal NV_ID { get; set; }
        public string maNV { get; set; }
        public string somay { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string quoctich { get; set; }
        public string soCMND { get; set; }
        public Nullable<System.DateTime> ngaycap { get; set; }
        public string noicap { get; set; }
        public string diachithuongtru { get; set; }
        public string diachitamtru { get; set; }
        public string masothue { get; set; }
        public string SDT_NV { get; set; }
        public string SDT_codinh { get; set; }
        public string maPB { get; set; }
        public Nullable<decimal> TO_ID { get; set; }
        public string CUON_GCS { get; set; }
        public Nullable<int> ChucvuID { get; set; }
        public Nullable<bool> isxoathanhtoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HD> CHITIET_HD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGAN> DANGNGANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGAN> DANGNGANs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGANCK> DANGNGANCKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGANCK> DANGNGANCKs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGANKH> DANGNGANKHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNGANKH> DANGNGANKHs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_KYGHI> DM_KYGHI { get; set; }
        public virtual DM_PHONGBAN DM_PHONGBAN { get; set; }
        public virtual DM_TO DM_TO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_THUTIENNUOC> LOG_THUTIENNUOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINH> LOTRINHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINH_GHI> LOTRINH_GHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINH_THU> LOTRINH_THU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAU_HD> MAU_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_HOADON> NHANVIEN_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_HOADON> NHANVIEN_HOADON1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_HOADON> NHANVIEN_HOADON2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_LNV> NHANVIEN_LNV { get; set; }
    }
}
