//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDC_CHITIETHD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDC_CHITIETHD()
        {
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
        }
    
        public string CUST_ID { get; set; }
        public string STT { get; set; }
        public string maDT { get; set; }
        public string m3tieuthu { get; set; }
        public string gianuoc { get; set; }
        public string m3BVMT { get; set; }
        public string phiBVMT { get; set; }
        public decimal chitietTDC_id { get; set; }
        public Nullable<int> nam { get; set; }
        public string kyghi { get; set; }
        public Nullable<decimal> dot_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
    }
}
