//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public string GUID { get; set; }
        public string FKEY { get; set; }
        public string SO_PT { get; set; }
        public string KY_HIEU_PT { get; set; }
        public string SO_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string SERI { get; set; }
        public decimal MA_KH { get; set; }
        public decimal ACCOUNT { get; set; }
        public string SO_HDG { get; set; }
        public string TEN_KH { get; set; }
        public string DIA_CHI { get; set; }
        public string TEL_PHONE { get; set; }
        public string EMAIL { get; set; }
        public string MA_THUE { get; set; }
        public string HTTT { get; set; }
        public string LOAI_PH { get; set; }
        public Nullable<int> THANG_PS { get; set; }
        public int HDDT { get; set; }
        public Nullable<System.DateTime> NGAY_PHAT_HANH { get; set; }
        public Nullable<System.DateTime> ngay_thu_tien { get; set; }
        public System.DateTime ngay_thuc_hien { get; set; }
        public string so_bo { get; set; }
        public string loai_kh { get; set; }
        public string gia_nk { get; set; }
        public Nullable<int> cs_cu { get; set; }
        public Nullable<int> cs_moi { get; set; }
        public Nullable<decimal> m3tt { get; set; }
        public Nullable<decimal> tienluubo { get; set; }
        public Nullable<decimal> tienpbvmt { get; set; }
        public Nullable<decimal> tienpnt { get; set; }
        public Nullable<decimal> TIEN_HANG { get; set; }
        public int TIEN_GIAM_TRU { get; set; }
        public Nullable<decimal> THUE_GTGT { get; set; }
        public Nullable<decimal> TIEN_THUE { get; set; }
        public Nullable<decimal> TONG_TIEN { get; set; }
        public Nullable<decimal> tong_thu { get; set; }
        public int CHECKS { get; set; }
        public string MA_DV { get; set; }
        public string ma_tuyen_cuoc { get; set; }
        public string nv_id { get; set; }
        public string ma_nd { get; set; }
        public Nullable<double> locationX { get; set; }
        public Nullable<double> locationY { get; set; }
        public Nullable<decimal> dot_id { get; set; }
        public Nullable<int> dmkh { get; set; }
        public string mtt { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public Nullable<int> mgb { get; set; }
        public string ghichu_dc { get; set; }
    }
}
