//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIEUTHU
    {
        public string IDKH { get; set; }
        public int NAM { get; set; }
        public int THANG { get; set; }
        public string IDKHCU { get; set; }
        public string MADP { get; set; }
        public string SODB { get; set; }
        public string MALT { get; set; }
        public string MAY { get; set; }
        public string TO { get; set; }
        public string DOT { get; set; }
        public string MADB { get; set; }
        public Nullable<int> STT { get; set; }
        public string MALKH { get; set; }
        public string MAMDSD { get; set; }
        public string MABG { get; set; }
        public string MAKV { get; set; }
        public string TTSD { get; set; }
        public string LOAICUP { get; set; }
        public Nullable<bool> ISHUY { get; set; }
        public string TENKH { get; set; }
        public string SONHA { get; set; }
        public string TENDUONG { get; set; }
        public string MAQUAN { get; set; }
        public string MAPHUONG { get; set; }
        public Nullable<int> DINHMUC { get; set; }
        public Nullable<int> CHISODAU { get; set; }
        public Nullable<int> CHISOCUOI { get; set; }
        public Nullable<int> KLTIEUTHU { get; set; }
        public Nullable<int> TBTT { get; set; }
        public Nullable<int> TAMTINH { get; set; }
        public string CODEMOI { get; set; }
        public string TTDH { get; set; }
        public string TTHAIGHI { get; set; }
        public string THBT { get; set; }
        public Nullable<double> TIENNUOC { get; set; }
        public Nullable<double> TIENPHIMT { get; set; }
        public Nullable<double> TIENTHUE { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public Nullable<bool> ISGCS { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public string GHICHUCS { get; set; }
        public string MANVNCS { get; set; }
        public Nullable<System.DateTime> NGAYNHAPCS { get; set; }
        public Nullable<int> CHISODAU_T1 { get; set; }
        public Nullable<int> CHISOCUOI_T1 { get; set; }
        public Nullable<int> KLTIEUTHU_T1 { get; set; }
        public string CODE_T1 { get; set; }
        public string TTDH_T1 { get; set; }
        public Nullable<int> CHISODAU_T2 { get; set; }
        public Nullable<int> CHISOCUOI_T2 { get; set; }
        public Nullable<int> KLTIEUTHU_T2 { get; set; }
        public string CODE_T2 { get; set; }
        public string TTDH_T2 { get; set; }
        public Nullable<int> CHISODAU_T3 { get; set; }
        public Nullable<int> CHISOCUOI_T3 { get; set; }
        public Nullable<int> KLTIEUTHU_T3 { get; set; }
        public string CODE_T3 { get; set; }
        public string TTDH_T3 { get; set; }
        public string MALDH { get; set; }
        public string MALDH_MOI { get; set; }
        public string MADH { get; set; }
        public string MADH_MOI { get; set; }
        public Nullable<int> CSTDH { get; set; }
        public Nullable<int> CSLDH { get; set; }
        public Nullable<System.DateTime> NGAYTDH { get; set; }
        public Nullable<System.DateTime> NGAYLDH { get; set; }
        public string SONHAMOI { get; set; }
        public string TENDUONGMOI { get; set; }
        public Nullable<int> KICHCOMOI { get; set; }
        public Nullable<int> VITRI { get; set; }
        public Nullable<int> STTMOI { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public string GHICHUMH { get; set; }
        public string MANVMH { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public Nullable<bool> ISMH { get; set; }
    
        public virtual KHACHHANG_TDC KHACHHANG_TDC { get; set; }
    }
}
