//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWTHONGTINHOADON
    {
        public string hoten { get; set; }
        public decimal ID_HD { get; set; }
        public string kyghi { get; set; }
        public Nullable<int> nam { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public string quan { get; set; }
        public string phuong { get; set; }
        public string hotenNV { get; set; }
        public string SO_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string tentrangthai { get; set; }
        public string chitiet { get; set; }
        public string chuyendoi { get; set; }
        public string dongbo { get; set; }
        public string thanhtoan { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<decimal> trangthai_id { get; set; }
        public string seri { get; set; }
        public string MaLT { get; set; }
        public Nullable<System.DateTime> NGAYDANGNGAN_NV { get; set; }
        public string ghichu { get; set; }
        public string trangthaiKH { get; set; }
        public string dieuchinh { get; set; }
    }
}
