//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_LOGTHUTIENNUOC
    {
        public Nullable<decimal> TO_ID { get; set; }
        public string nhanvien { get; set; }
        public string maLT { get; set; }
        public string madanhbo { get; set; }
        public string hoten_KH { get; set; }
        public string ten_kyghi { get; set; }
        public string kyghi { get; set; }
        public string diachi { get; set; }
        public string loaigiay { get; set; }
        public System.DateTime NGAYIN { get; set; }
        public string seri { get; set; }
        public decimal NV_ID { get; set; }
        public int GIAYBAO { get; set; }
        public Nullable<decimal> tongtien { get; set; }
    }
}
