//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_TDC_WEBSERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUCAU_DIEUCHINH
    {
        public decimal QD_ID { get; set; }
        public Nullable<decimal> IDHD { get; set; }
        public Nullable<decimal> IDKH { get; set; }
        public string kyghi { get; set; }
        public Nullable<System.DateTime> ngay_DC { get; set; }
        public Nullable<int> m3_DC { get; set; }
        public Nullable<decimal> tiennuoc_DC { get; set; }
        public Nullable<decimal> tienthue_DC { get; set; }
        public Nullable<decimal> tienBVMT_DC { get; set; }
        public Nullable<decimal> tongtien_DC { get; set; }
        public Nullable<bool> isDH { get; set; }
        public Nullable<bool> isDS { get; set; }
        public Nullable<bool> isDG { get; set; }
        public Nullable<bool> isMH { get; set; }
        public Nullable<bool> isTB { get; set; }
        public Nullable<bool> isIn { get; set; }
        public Nullable<bool> isBOT { get; set; }
        public Nullable<bool> iskhac { get; set; }
        public Nullable<System.DateTime> ngayPH { get; set; }
        public string SO_QD { get; set; }
        public Nullable<System.DateTime> ngayin { get; set; }
        public string bangchu { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> isdaduyet { get; set; }
        public Nullable<decimal> user_create { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<decimal> user_update { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public Nullable<int> loaiDC { get; set; }
        public Nullable<int> m3PT { get; set; }
        public Nullable<decimal> tiennuoc_PT { get; set; }
        public Nullable<decimal> tienthue_PT { get; set; }
        public Nullable<decimal> tienBVMT_PT { get; set; }
        public Nullable<decimal> tongtien_PT { get; set; }
        public Nullable<bool> isCTY { get; set; }
        public Nullable<bool> isTCT { get; set; }
        public Nullable<int> trangthai { get; set; }
    }
}
