//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://capnuocthuducservice.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string WASSPRO_TNT_Business_BusinessService {
            get {
                return ((string)(this["WASSPRO_TNT_Business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://tdapi.capnuocthuduc.vn/thuho.asmx")]
        public string WASSPRO_TDC_ServiceTDC_ThuHo {
            get {
                return ((string)(this["WASSPRO_TDC_ServiceTDC_ThuHo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://capnuocthuducservice.vnpt-invoice.com.vn/PortalService.asmx")]
        public string WASSPRO_TDC_Portal_PortalService {
            get {
                return ((string)(this["WASSPRO_TDC_Portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://capnuocthuducservice.vnpt-invoice.com.vn/PublishService.asmx")]
        public string WASSPRO_TDC_Publish_PublishService {
            get {
                return ((string)(this["WASSPRO_TDC_Publish_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://capnuocthuduc-tt78admindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string WASSPRO_TDC_ws78demo_PublishService {
            get {
                return ((string)(this["WASSPRO_TDC_ws78demo_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://capnuocthuduc-tt78admin.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string WASSPRO_TDC_bs78_BusinessService {
            get {
                return ((string)(this["WASSPRO_TDC_bs78_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://capnuocthuduc-tt78admin.vnpt-invoice.com.vn/Publishservice.asmx")]
        public string WASSPRO_TDC_pb78_PublishService {
            get {
                return ((string)(this["WASSPRO_TDC_pb78_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://capnuocthuduc-tt78admin.vnpt-invoice.com.vn/Portalservice.asmx")]
        public string WASSPRO_TDC_portal78_PortalService {
            get {
                return ((string)(this["WASSPRO_TDC_portal78_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.24.63;Initial Catalog=CAPNUOC_TDC;Persist Security Info=True;" +
            "User ID=sa;Password=sqlSA@Admin;TrustServerCertificate=True")]
        public string CAPNUOC_TDCConnectionString {
            get {
                return ((string)(this["CAPNUOC_TDCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=QLCongNo.capnuocthuduc.vn,11001;Initial Catalog=CAPNUOC_TDC;Persist S" +
            "ecurity Info=True;User ID=wasspro_tdc;Password=wtdc@123")]
        public string CAPNUOC_TNCConnectionString {
            get {
                return ((string)(this["CAPNUOC_TNCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=QLCongNo.capnuocthuduc.vn,11001;Initial Catalog=CAPNUOC_TDC_TEST;User" +
            " ID=wasspro_tdc;Password=wtdc@123")]
        public string CAPNUOC_TDC_TESTConnectionString {
            get {
                return ((string)(this["CAPNUOC_TDC_TESTConnectionString"]));
            }
        }
    }
}
