//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGGIA_DM
    {
        public decimal dinhmuc_id { get; set; }
        public string magia { get; set; }
        public bool theoNK { get; set; }
        public decimal denm3 { get; set; }
        public Nullable<decimal> dentile { get; set; }
        public string maDT { get; set; }
    
        public virtual BANGGIA BANGGIA { get; set; }
        public virtual DOITUONGSUDUNG DOITUONGSUDUNG { get; set; }
    }
}
