//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHISONUOC
    {
        public decimal id_chisonuoc { get; set; }
        public string ID_kyghi { get; set; }
        public decimal ID_KH { get; set; }
        public string madanhbo { get; set; }
        public Nullable<decimal> chisomoi { get; set; }
        public Nullable<int> luongtieuthu { get; set; }
        public Nullable<System.DateTime> ngayghi { get; set; }
        public Nullable<decimal> chisocu { get; set; }
        public Nullable<System.DateTime> ngayghichisocu { get; set; }
        public Nullable<long> tieuthukytruoc { get; set; }
        public Nullable<long> tieuthukytruoc2 { get; set; }
        public Nullable<long> tieuthukytruoc3 { get; set; }
        public string NVghi { get; set; }
        public Nullable<decimal> chisotanggiam { get; set; }
        public Nullable<int> GHICHU_ID { get; set; }
        public Nullable<bool> daxuly { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string nvcapnhat { get; set; }
        public Nullable<decimal> co_id_hd { get; set; }
        public string noidung_xuly { get; set; }
        public Nullable<bool> bat_thuong { get; set; }
        public string notes { get; set; }
        public Nullable<bool> chuatinhtien { get; set; }
        public Nullable<decimal> VAT_app { get; set; }
        public Nullable<decimal> tienhang_app { get; set; }
        public Nullable<decimal> tienthue_app { get; set; }
        public Nullable<decimal> thanhtien_app { get; set; }
        public Nullable<bool> thutien_app { get; set; }
        public string products_app { get; set; }
        public Nullable<decimal> tienbvmt_app { get; set; }
        public Nullable<decimal> luubo_app { get; set; }
        public Nullable<decimal> cscu_DHthay { get; set; }
        public Nullable<decimal> csmoi_DHthay { get; set; }
    
        public virtual DANHMUCKYGHI DANHMUCKYGHI { get; set; }
        public virtual DMGHICHU DMGHICHU { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
