//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HD
    {
        public decimal ID_chitiet_HD { get; set; }
        public decimal ID_HD { get; set; }
        public Nullable<decimal> tum3 { get; set; }
        public Nullable<decimal> denm3 { get; set; }
        public Nullable<decimal> dongia0v { get; set; }
        public Nullable<decimal> thanhtien0v { get; set; }
        public string diengiai { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
        public Nullable<decimal> soluong { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
