//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGTU
    {
        public decimal ID_CT { get; set; }
        public System.DateTime ngaylap { get; set; }
        public int NV_ID_nop { get; set; }
        public decimal tongtien { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public string ghichu { get; set; }
        public string maloai { get; set; }
        public int NV_ID_lap { get; set; }
        public string ID_kyghi { get; set; }
        public string SOCT { get; set; }
        public Nullable<System.DateTime> ngayct { get; set; }
    
        public virtual DANHMUCKYGHI DANHMUCKYGHI { get; set; }
        public virtual LOAICHUNGTU LOAICHUNGTU { get; set; }
    }
}
