//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGTU_HOADON
    {
        public decimal ID_CT { get; set; }
        public decimal ID_HD { get; set; }
        public decimal sotien { get; set; }
        public Nullable<bool> dadongbo { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
