//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCKYGHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHMUCKYGHI()
        {
            this.CHISONUOCs = new HashSet<CHISONUOC>();
            this.CHUNGTUs = new HashSet<CHUNGTU>();
        }
    
        public string ID_kyghi { get; set; }
        public string ten_kyghi { get; set; }
        public int thang { get; set; }
        public int nam { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaycapnhat { get; set; }
        public Nullable<bool> chuyenno { get; set; }
        public Nullable<bool> hoadon { get; set; }
        public Nullable<bool> gachno { get; set; }
        public Nullable<bool> ghinuoc { get; set; }
        public Nullable<bool> thuno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHISONUOC> CHISONUOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUNGTU> CHUNGTUs { get; set; }
    }
}
