//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CAPNUOC_LDGEntities : DbContext
    {
        public CAPNUOC_LDGEntities()
            : base("name=CAPNUOC_LDGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGGIA> BANGGIAs { get; set; }
        public virtual DbSet<BANGGIA_DM> BANGGIA_DM { get; set; }
        public virtual DbSet<BD_KHACHHANG> BD_KHACHHANG { get; set; }
        public virtual DbSet<CHINHANH> CHINHANHs { get; set; }
        public virtual DbSet<CHISONUOC> CHISONUOCs { get; set; }
        public virtual DbSet<CHITIET_HD> CHITIET_HD { get; set; }
        public virtual DbSet<CHITIET_HD_EDIT> CHITIET_HD_EDIT { get; set; }
        public virtual DbSet<CHUNGTU> CHUNGTUs { get; set; }
        public virtual DbSet<CHUNGTU_CHISONUOC> CHUNGTU_CHISONUOC { get; set; }
        public virtual DbSet<CHUNGTU_HOADON> CHUNGTU_HOADON { get; set; }
        public virtual DbSet<CONGTY> CONGTies { get; set; }
        public virtual DbSet<DANHMUCKYGHI> DANHMUCKYGHIs { get; set; }
        public virtual DbSet<DANHMUCTRANGTHAI> DANHMUCTRANGTHAIs { get; set; }
        public virtual DbSet<DM_LYDO> DM_LYDO { get; set; }
        public virtual DbSet<DM_NGANHANG> DM_NGANHANG { get; set; }
        public virtual DbSet<dm_phieu_thu> dm_phieu_thu { get; set; }
        public virtual DbSet<DMGHICHU> DMGHICHUs { get; set; }
        public virtual DbSet<DMNGUYENNHAN> DMNGUYENNHANs { get; set; }
        public virtual DbSet<DMTRANGTHAI_HD> DMTRANGTHAI_HD { get; set; }
        public virtual DbSet<DMTRANGTHAI_YC> DMTRANGTHAI_YC { get; set; }
        public virtual DbSet<DOITUONGSUDUNG> DOITUONGSUDUNGs { get; set; }
        public virtual DbSet<DUONG> DUONGs { get; set; }
        public virtual DbSet<DUONG_PHUONG> DUONG_PHUONG { get; set; }
        public virtual DbSet<GiaBVMT> GiaBVMTs { get; set; }
        public virtual DbSet<GiaoPhieu> GiaoPhieux { get; set; }
        public virtual DbSet<HIEUDONGHO> HIEUDONGHOes { get; set; }
        public virtual DbSet<HINHTHUCTHANHTOAN> HINHTHUCTHANHTOANs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HOADON_HUY> HOADON_HUY { get; set; }
        public virtual DbSet<HOADON_LOG> HOADON_LOG { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUVUC> KHUVUCs { get; set; }
        public virtual DbSet<KICHCODH> KICHCODHs { get; set; }
        public virtual DbSet<LOAICHUNGTU> LOAICHUNGTUs { get; set; }
        public virtual DbSet<LOAINHANVIEN> LOAINHANVIENs { get; set; }
        public virtual DbSet<LOAIYEUCAU> LOAIYEUCAUs { get; set; }
        public virtual DbSet<LOG_USER> LOG_USER { get; set; }
        public virtual DbSet<LOTRINH> LOTRINHs { get; set; }
        public virtual DbSet<LOTRINH_GHI> LOTRINH_GHI { get; set; }
        public virtual DbSet<LOTRINH_THU> LOTRINH_THU { get; set; }
        public virtual DbSet<LTPhu> LTPhus { get; set; }
        public virtual DbSet<MAU_HD> MAU_HD { get; set; }
        public virtual DbSet<NGANHNGHE> NGANHNGHEs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NGUOIDUNG_QUYEN> NGUOIDUNG_QUYEN { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHANVIEN_LNV> NHANVIEN_LNV { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<PHUONG> PHUONGs { get; set; }
        public virtual DbSet<PublishedInvoice> PublishedInvoices { get; set; }
        public virtual DbSet<QUAN> QUANs { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<QUYEN_MENU> QUYEN_MENU { get; set; }
        public virtual DbSet<STT_DONGIA> STT_DONGIA { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN_SERVICE> TAIKHOAN_SERVICE { get; set; }
        public virtual DbSet<TINH> TINHs { get; set; }
        public virtual DbSet<YEUCAU> YEUCAUs { get; set; }
        public virtual DbSet<DSTAM> DSTAMs { get; set; }
        public virtual DbSet<NHOMDOITUONG> NHOMDOITUONGs { get; set; }
        public virtual DbSet<PublishedInvoicesbk29122017> PublishedInvoicesbk29122017 { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DOANHTHU> DOANHTHUs { get; set; }
        public virtual DbSet<DSBIENNHAN> DSBIENNHANs { get; set; }
        public virtual DbSet<DSBIENNHANH_APP> DSBIENNHANH_APP { get; set; }
        public virtual DbSet<DSHD_PhieuThu> DSHD_PhieuThu { get; set; }
        public virtual DbSet<DSHOADON> DSHOADONs { get; set; }
        public virtual DbSet<DSPHIEUTHU_APP> DSPHIEUTHU_APP { get; set; }
        public virtual DbSet<Thongkedoanhthu> Thongkedoanhthus { get; set; }
    
        [DbFunction("CAPNUOC_LDGEntities", "fngetDatakycuoc")]
        public virtual IQueryable<fngetDatakycuoc_Result> fngetDatakycuoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fngetDatakycuoc_Result>("[CAPNUOC_LDGEntities].[fngetDatakycuoc]()");
        }
    
        [DbFunction("CAPNUOC_LDGEntities", "fngetDataLoTrinh")]
        public virtual IQueryable<fngetDataLoTrinh_Result> fngetDataLoTrinh(string username, string loailotrinh)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var loailotrinhParameter = loailotrinh != null ?
                new ObjectParameter("loailotrinh", loailotrinh) :
                new ObjectParameter("loailotrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fngetDataLoTrinh_Result>("[CAPNUOC_LDGEntities].[fngetDataLoTrinh](@username, @loailotrinh)", usernameParameter, loailotrinhParameter);
        }
    
        public virtual int GACHNO_APP_CT(Nullable<decimal> id_ct)
        {
            var id_ctParameter = id_ct.HasValue ?
                new ObjectParameter("id_ct", id_ct) :
                new ObjectParameter("id_ct", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GACHNO_APP_CT", id_ctParameter);
        }
    
        public virtual int GACHNO_NVTHU(string kyghi, string soct, Nullable<int> nv_id, Nullable<System.DateTime> ngaythu)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var soctParameter = soct != null ?
                new ObjectParameter("soct", soct) :
                new ObjectParameter("soct", typeof(string));
    
            var nv_idParameter = nv_id.HasValue ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(int));
    
            var ngaythuParameter = ngaythu.HasValue ?
                new ObjectParameter("ngaythu", ngaythu) :
                new ObjectParameter("ngaythu", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GACHNO_NVTHU", kyghiParameter, soctParameter, nv_idParameter, ngaythuParameter);
        }
    
        public virtual ObjectResult<string> GetNVByYC(Nullable<decimal> yc)
        {
            var ycParameter = yc.HasValue ?
                new ObjectParameter("yc", yc) :
                new ObjectParameter("yc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetNVByYC", ycParameter);
        }
    
        public virtual int InsertCSN(string iD_KYGHI, string iD_KYGHI_MOI, Nullable<decimal> id_kh)
        {
            var iD_KYGHIParameter = iD_KYGHI != null ?
                new ObjectParameter("ID_KYGHI", iD_KYGHI) :
                new ObjectParameter("ID_KYGHI", typeof(string));
    
            var iD_KYGHI_MOIParameter = iD_KYGHI_MOI != null ?
                new ObjectParameter("ID_KYGHI_MOI", iD_KYGHI_MOI) :
                new ObjectParameter("ID_KYGHI_MOI", typeof(string));
    
            var id_khParameter = id_kh.HasValue ?
                new ObjectParameter("id_kh", id_kh) :
                new ObjectParameter("id_kh", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCSN", iD_KYGHIParameter, iD_KYGHI_MOIParameter, id_khParameter);
        }
    
        public virtual int InsPublishedInvoice(string kEY, Nullable<decimal> iDKH, string kYHD, Nullable<decimal> sOPHIEU, string sO_HD, string kY_HIEU_HD, string mAU_HD, string sODB, string hOTEN, string dIACHI, string mST, string gIANK, Nullable<decimal> cSCU, Nullable<decimal> cSMOI, Nullable<decimal> m3TT, string pRODUCTS, Nullable<decimal> cONGTHANHTIEN, Nullable<decimal> tIENLUUBO, Nullable<decimal> vAT, Nullable<decimal> tIENVAT, Nullable<decimal> gIABVMT, Nullable<decimal> pBVMT4M3, Nullable<decimal> tIENPBVMT, Nullable<decimal> giaNthai, Nullable<decimal> pNT4M3, Nullable<decimal> tIENPNT, Nullable<decimal> tienthueDH, Nullable<decimal> tienvthueDH, Nullable<decimal> tONGCONG, string mAHTTT, string ma_tuyen_cuoc)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var iDKHParameter = iDKH.HasValue ?
                new ObjectParameter("IDKH", iDKH) :
                new ObjectParameter("IDKH", typeof(decimal));
    
            var kYHDParameter = kYHD != null ?
                new ObjectParameter("KYHD", kYHD) :
                new ObjectParameter("KYHD", typeof(string));
    
            var sOPHIEUParameter = sOPHIEU.HasValue ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(decimal));
    
            var sO_HDParameter = sO_HD != null ?
                new ObjectParameter("SO_HD", sO_HD) :
                new ObjectParameter("SO_HD", typeof(string));
    
            var kY_HIEU_HDParameter = kY_HIEU_HD != null ?
                new ObjectParameter("KY_HIEU_HD", kY_HIEU_HD) :
                new ObjectParameter("KY_HIEU_HD", typeof(string));
    
            var mAU_HDParameter = mAU_HD != null ?
                new ObjectParameter("MAU_HD", mAU_HD) :
                new ObjectParameter("MAU_HD", typeof(string));
    
            var sODBParameter = sODB != null ?
                new ObjectParameter("SODB", sODB) :
                new ObjectParameter("SODB", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var mSTParameter = mST != null ?
                new ObjectParameter("MST", mST) :
                new ObjectParameter("MST", typeof(string));
    
            var gIANKParameter = gIANK != null ?
                new ObjectParameter("GIANK", gIANK) :
                new ObjectParameter("GIANK", typeof(string));
    
            var cSCUParameter = cSCU.HasValue ?
                new ObjectParameter("CSCU", cSCU) :
                new ObjectParameter("CSCU", typeof(decimal));
    
            var cSMOIParameter = cSMOI.HasValue ?
                new ObjectParameter("CSMOI", cSMOI) :
                new ObjectParameter("CSMOI", typeof(decimal));
    
            var m3TTParameter = m3TT.HasValue ?
                new ObjectParameter("M3TT", m3TT) :
                new ObjectParameter("M3TT", typeof(decimal));
    
            var pRODUCTSParameter = pRODUCTS != null ?
                new ObjectParameter("PRODUCTS", pRODUCTS) :
                new ObjectParameter("PRODUCTS", typeof(string));
    
            var cONGTHANHTIENParameter = cONGTHANHTIEN.HasValue ?
                new ObjectParameter("CONGTHANHTIEN", cONGTHANHTIEN) :
                new ObjectParameter("CONGTHANHTIEN", typeof(decimal));
    
            var tIENLUUBOParameter = tIENLUUBO.HasValue ?
                new ObjectParameter("TIENLUUBO", tIENLUUBO) :
                new ObjectParameter("TIENLUUBO", typeof(decimal));
    
            var vATParameter = vAT.HasValue ?
                new ObjectParameter("VAT", vAT) :
                new ObjectParameter("VAT", typeof(decimal));
    
            var tIENVATParameter = tIENVAT.HasValue ?
                new ObjectParameter("TIENVAT", tIENVAT) :
                new ObjectParameter("TIENVAT", typeof(decimal));
    
            var gIABVMTParameter = gIABVMT.HasValue ?
                new ObjectParameter("GIABVMT", gIABVMT) :
                new ObjectParameter("GIABVMT", typeof(decimal));
    
            var pBVMT4M3Parameter = pBVMT4M3.HasValue ?
                new ObjectParameter("PBVMT4M3", pBVMT4M3) :
                new ObjectParameter("PBVMT4M3", typeof(decimal));
    
            var tIENPBVMTParameter = tIENPBVMT.HasValue ?
                new ObjectParameter("TIENPBVMT", tIENPBVMT) :
                new ObjectParameter("TIENPBVMT", typeof(decimal));
    
            var giaNthaiParameter = giaNthai.HasValue ?
                new ObjectParameter("GiaNthai", giaNthai) :
                new ObjectParameter("GiaNthai", typeof(decimal));
    
            var pNT4M3Parameter = pNT4M3.HasValue ?
                new ObjectParameter("PNT4M3", pNT4M3) :
                new ObjectParameter("PNT4M3", typeof(decimal));
    
            var tIENPNTParameter = tIENPNT.HasValue ?
                new ObjectParameter("TIENPNT", tIENPNT) :
                new ObjectParameter("TIENPNT", typeof(decimal));
    
            var tienthueDHParameter = tienthueDH.HasValue ?
                new ObjectParameter("TienthueDH", tienthueDH) :
                new ObjectParameter("TienthueDH", typeof(decimal));
    
            var tienvthueDHParameter = tienvthueDH.HasValue ?
                new ObjectParameter("TienvthueDH", tienvthueDH) :
                new ObjectParameter("TienvthueDH", typeof(decimal));
    
            var tONGCONGParameter = tONGCONG.HasValue ?
                new ObjectParameter("TONGCONG", tONGCONG) :
                new ObjectParameter("TONGCONG", typeof(decimal));
    
            var mAHTTTParameter = mAHTTT != null ?
                new ObjectParameter("MAHTTT", mAHTTT) :
                new ObjectParameter("MAHTTT", typeof(string));
    
            var ma_tuyen_cuocParameter = ma_tuyen_cuoc != null ?
                new ObjectParameter("ma_tuyen_cuoc", ma_tuyen_cuoc) :
                new ObjectParameter("ma_tuyen_cuoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsPublishedInvoice", kEYParameter, iDKHParameter, kYHDParameter, sOPHIEUParameter, sO_HDParameter, kY_HIEU_HDParameter, mAU_HDParameter, sODBParameter, hOTENParameter, dIACHIParameter, mSTParameter, gIANKParameter, cSCUParameter, cSMOIParameter, m3TTParameter, pRODUCTSParameter, cONGTHANHTIENParameter, tIENLUUBOParameter, vATParameter, tIENVATParameter, gIABVMTParameter, pBVMT4M3Parameter, tIENPBVMTParameter, giaNthaiParameter, pNT4M3Parameter, tIENPNTParameter, tienthueDHParameter, tienvthueDHParameter, tONGCONGParameter, mAHTTTParameter, ma_tuyen_cuocParameter);
        }
    
        public virtual int KYGHI(string iD_KYGHI, string iD_KYGHI_MOI)
        {
            var iD_KYGHIParameter = iD_KYGHI != null ?
                new ObjectParameter("ID_KYGHI", iD_KYGHI) :
                new ObjectParameter("ID_KYGHI", typeof(string));
    
            var iD_KYGHI_MOIParameter = iD_KYGHI_MOI != null ?
                new ObjectParameter("ID_KYGHI_MOI", iD_KYGHI_MOI) :
                new ObjectParameter("ID_KYGHI_MOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KYGHI", iD_KYGHIParameter, iD_KYGHI_MOIParameter);
        }
    
        public virtual ObjectResult<RPBangKeBienNhan_Result> RPBangKeBienNhan(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPBangKeBienNhan_Result>("RPBangKeBienNhan", kyghiParameter);
        }
    
        public virtual ObjectResult<RPBangKeHoaDon_Result> RPBangKeHoaDon(string maLT, string kyghi)
        {
            var maLTParameter = maLT != null ?
                new ObjectParameter("maLT", maLT) :
                new ObjectParameter("maLT", typeof(string));
    
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPBangKeHoaDon_Result>("RPBangKeHoaDon", maLTParameter, kyghiParameter);
        }
    
        public virtual ObjectResult<RPBangKeHuyHD_Result> RPBangKeHuyHD(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPBangKeHuyHD_Result>("RPBangKeHuyHD", kyghiParameter);
        }
    
        public virtual ObjectResult<RPBaoCaoHDTon_LT_Result> RPBaoCaoHDTon_LT(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPBaoCaoHDTon_LT_Result>("RPBaoCaoHDTon_LT", kyghiParameter);
        }
    
        public virtual ObjectResult<RPBaoCaoTongHop_Result> RPBaoCaoTongHop(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPBaoCaoTongHop_Result>("RPBaoCaoTongHop", kyghiParameter);
        }
    
        public virtual ObjectResult<RPChiTietHD_Result> RPChiTietHD(string iD_HD)
        {
            var iD_HDParameter = iD_HD != null ?
                new ObjectParameter("ID_HD", iD_HD) :
                new ObjectParameter("ID_HD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPChiTietHD_Result>("RPChiTietHD", iD_HDParameter);
        }
    
        public virtual ObjectResult<RPChiTietThuLoTrinh_Result> RPChiTietThuLoTrinh(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPChiTietThuLoTrinh_Result>("RPChiTietThuLoTrinh", kyghiParameter);
        }
    
        public virtual ObjectResult<RPChiTietThuLT_Result> RPChiTietThuLT(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPChiTietThuLT_Result>("RPChiTietThuLT", kyghiParameter);
        }
    
        public virtual ObjectResult<RPChiTietThuLTTheoNgay_Result> RPChiTietThuLTTheoNgay(string kyghi, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string kyghi_gn)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var kyghi_gnParameter = kyghi_gn != null ?
                new ObjectParameter("kyghi_gn", kyghi_gn) :
                new ObjectParameter("kyghi_gn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPChiTietThuLTTheoNgay_Result>("RPChiTietThuLTTheoNgay", kyghiParameter, tungayParameter, denngayParameter, kyghi_gnParameter);
        }
    
        public virtual ObjectResult<RPDoanhThuTienNuoc_Result> RPDoanhThuTienNuoc(string maCN, Nullable<int> nam, string kyghi)
        {
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPDoanhThuTienNuoc_Result>("RPDoanhThuTienNuoc", maCNParameter, namParameter, kyghiParameter);
        }
    
        public virtual ObjectResult<RPGiayBaoTienNuoc_Result> RPGiayBaoTienNuoc(string iD_HD)
        {
            var iD_HDParameter = iD_HD != null ?
                new ObjectParameter("ID_HD", iD_HD) :
                new ObjectParameter("ID_HD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPGiayBaoTienNuoc_Result>("RPGiayBaoTienNuoc", iD_HDParameter);
        }
    
        public virtual ObjectResult<RPHDTonNgungNuoc_Result> RPHDTonNgungNuoc(string kyghi, Nullable<int> maHTTT, string maCN, Nullable<System.DateTime> tungay, Nullable<System.DateTime> dennngay)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var maHTTTParameter = maHTTT.HasValue ?
                new ObjectParameter("maHTTT", maHTTT) :
                new ObjectParameter("maHTTT", typeof(int));
    
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var dennngayParameter = dennngay.HasValue ?
                new ObjectParameter("dennngay", dennngay) :
                new ObjectParameter("dennngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPHDTonNgungNuoc_Result>("RPHDTonNgungNuoc", kyghiParameter, maHTTTParameter, maCNParameter, tungayParameter, dennngayParameter);
        }
    
        public virtual ObjectResult<RPHoaDonTon_Result> RPHoaDonTon(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPHoaDonTon_Result>("RPHoaDonTon", kyghiParameter);
        }
    
        public virtual ObjectResult<RPHoaDonTonNamTheoKyGhi_Result> RPHoaDonTonNamTheoKyGhi(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPHoaDonTonNamTheoKyGhi_Result>("RPHoaDonTonNamTheoKyGhi", kyghiParameter);
        }
    
        public virtual ObjectResult<RPKhachHangPhatSinh_Result> RPKhachHangPhatSinh(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPKhachHangPhatSinh_Result>("RPKhachHangPhatSinh", ngaybdParameter, ngayktParameter);
        }
    
        public virtual ObjectResult<RPLuuBoTheoNhomGia_Result> RPLuuBoTheoNhomGia(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPLuuBoTheoNhomGia_Result>("RPLuuBoTheoNhomGia", kyghiParameter);
        }
    
        public virtual ObjectResult<RPNgungNuoc_Result> RPNgungNuoc(Nullable<decimal> iD_KH)
        {
            var iD_KHParameter = iD_KH.HasValue ?
                new ObjectParameter("ID_KH", iD_KH) :
                new ObjectParameter("ID_KH", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPNgungNuoc_Result>("RPNgungNuoc", iD_KHParameter);
        }
    
        public virtual ObjectResult<RPPhieuKiemTra_Result> RPPhieuKiemTra(Nullable<decimal> id_kh)
        {
            var id_khParameter = id_kh.HasValue ?
                new ObjectParameter("id_kh", id_kh) :
                new ObjectParameter("id_kh", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPPhieuKiemTra_Result>("RPPhieuKiemTra", id_khParameter);
        }
    
        public virtual ObjectResult<RPPhieuThuNV_Result> RPPhieuThuNV(string kyghi, string soCT)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var soCTParameter = soCT != null ?
                new ObjectParameter("soCT", soCT) :
                new ObjectParameter("soCT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPPhieuThuNV_Result>("RPPhieuThuNV", kyghiParameter, soCTParameter);
        }
    
        public virtual ObjectResult<RPQuyetToanHoaDon_Result> RPQuyetToanHoaDon(string kyghi, string maLT, Nullable<int> nV_ID)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var maLTParameter = maLT != null ?
                new ObjectParameter("maLT", maLT) :
                new ObjectParameter("maLT", typeof(string));
    
            var nV_IDParameter = nV_ID.HasValue ?
                new ObjectParameter("NV_ID", nV_ID) :
                new ObjectParameter("NV_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPQuyetToanHoaDon_Result>("RPQuyetToanHoaDon", kyghiParameter, maLTParameter, nV_IDParameter);
        }
    
        public virtual ObjectResult<RPSanLuongChuanThu_Result> RPSanLuongChuanThu(string kyghi, Nullable<int> nam, string maCN)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPSanLuongChuanThu_Result>("RPSanLuongChuanThu", kyghiParameter, namParameter, maCNParameter);
        }
    
        public virtual ObjectResult<RPSuDungNuoc_test_Result> RPSuDungNuoc_test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPSuDungNuoc_test_Result>("RPSuDungNuoc_test");
        }
    
        public virtual ObjectResult<RPThongKeDoiDH_Result> RPThongKeDoiDH(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, string maLT)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var maLTParameter = maLT != null ?
                new ObjectParameter("maLT", maLT) :
                new ObjectParameter("maLT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongKeDoiDH_Result>("RPThongKeDoiDH", ngaybdParameter, ngayktParameter, maLTParameter);
        }
    
        public virtual ObjectResult<RPThongKeHDTheoCachThu_Result> RPThongKeHDTheoCachThu(string kyghi, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, string maCN)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongKeHDTheoCachThu_Result>("RPThongKeHDTheoCachThu", kyghiParameter, ngaybdParameter, ngayktParameter, maCNParameter);
        }
    
        public virtual ObjectResult<RPThongKeSanLuongTheoCN_Result> RPThongKeSanLuongTheoCN(string cachthu, string kyghi)
        {
            var cachthuParameter = cachthu != null ?
                new ObjectParameter("cachthu", cachthu) :
                new ObjectParameter("cachthu", typeof(string));
    
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongKeSanLuongTheoCN_Result>("RPThongKeSanLuongTheoCN", cachthuParameter, kyghiParameter);
        }
    
        public virtual ObjectResult<RPThongKeSuDungNuoc_Result> RPThongKeSuDungNuoc(string kyghi, Nullable<int> nam, string maCN)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongKeSuDungNuoc_Result>("RPThongKeSuDungNuoc", kyghiParameter, namParameter, maCNParameter);
        }
    
        public virtual ObjectResult<RPThongKeSuDungNuoc_Nam_Result> RPThongKeSuDungNuoc_Nam(string nam, string maCN)
        {
            var namParameter = nam != null ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(string));
    
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongKeSuDungNuoc_Nam_Result>("RPThongKeSuDungNuoc_Nam", namParameter, maCNParameter);
        }
    
        public virtual ObjectResult<RPThongKeThongTin_Result> RPThongKeThongTin(string kyghi, Nullable<int> nam, string chinhanh)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongKeThongTin_Result>("RPThongKeThongTin", kyghiParameter, namParameter, chinhanhParameter);
        }
    
        public virtual ObjectResult<RPThongKeTonHDTheoNam_Result> RPThongKeTonHDTheoNam(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongKeTonHDTheoNam_Result>("RPThongKeTonHDTheoNam", namParameter);
        }
    
        public virtual ObjectResult<RPThongTin_Result> RPThongTin(string kyghi, string chinhanh)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThongTin_Result>("RPThongTin", kyghiParameter, chinhanhParameter);
        }
    
        public virtual ObjectResult<RPThuTon_HoaDon_Result> RPThuTon_HoaDon(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPThuTon_HoaDon_Result>("RPThuTon_HoaDon", kyghiParameter);
        }
    
        public virtual ObjectResult<RPTinhHinhSuDungHoaDon_Result> RPTinhHinhSuDungHoaDon(string kyghi)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPTinhHinhSuDungHoaDon_Result>("RPTinhHinhSuDungHoaDon", kyghiParameter);
        }
    
        public virtual ObjectResult<RPTonHoaDon_KH_Result> RPTonHoaDon_KH(string tukyghi, string denkyghi)
        {
            var tukyghiParameter = tukyghi != null ?
                new ObjectParameter("tukyghi", tukyghi) :
                new ObjectParameter("tukyghi", typeof(string));
    
            var denkyghiParameter = denkyghi != null ?
                new ObjectParameter("denkyghi", denkyghi) :
                new ObjectParameter("denkyghi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPTonHoaDon_KH_Result>("RPTonHoaDon_KH", tukyghiParameter, denkyghiParameter);
        }
    
        public virtual ObjectResult<RPTyLeThuTheoKy_Result> RPTyLeThuTheoKy(string kyghi, string maHTTT, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var maHTTTParameter = maHTTT != null ?
                new ObjectParameter("maHTTT", maHTTT) :
                new ObjectParameter("maHTTT", typeof(string));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPTyLeThuTheoKy_Result>("RPTyLeThuTheoKy", kyghiParameter, maHTTTParameter, ngaybdParameter, ngayktParameter);
        }
    
        public virtual ObjectResult<RPTyLeThuTheoNgay_Result> RPTyLeThuTheoNgay(string kyghi, Nullable<System.DateTime> ngaythu)
        {
            var kyghiParameter = kyghi != null ?
                new ObjectParameter("kyghi", kyghi) :
                new ObjectParameter("kyghi", typeof(string));
    
            var ngaythuParameter = ngaythu.HasValue ?
                new ObjectParameter("ngaythu", ngaythu) :
                new ObjectParameter("ngaythu", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPTyLeThuTheoNgay_Result>("RPTyLeThuTheoNgay", kyghiParameter, ngaythuParameter);
        }
    
        public virtual int SAPXEP_STT(string mALT)
        {
            var mALTParameter = mALT != null ?
                new ObjectParameter("MALT", mALT) :
                new ObjectParameter("MALT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SAPXEP_STT", mALTParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_getDataBangGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataBangGia");
        }
    
        public virtual int sp_getDataBaoCuoc(string mMadv, string maTuyenCuoc, string kyHoaDon)
        {
            var mMadvParameter = mMadv != null ?
                new ObjectParameter("mMadv", mMadv) :
                new ObjectParameter("mMadv", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            var kyHoaDonParameter = kyHoaDon != null ?
                new ObjectParameter("kyHoaDon", kyHoaDon) :
                new ObjectParameter("kyHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataBaoCuoc", mMadvParameter, maTuyenCuocParameter, kyHoaDonParameter);
        }
    
        public virtual int sp_getDataDoituongsudung()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataDoituongsudung");
        }
    
        public virtual int sp_getDataGhiChiSo(string mMaNhanvien, string maTuyenCuoc, string kyHoaDon)
        {
            var mMaNhanvienParameter = mMaNhanvien != null ?
                new ObjectParameter("mMaNhanvien", mMaNhanvien) :
                new ObjectParameter("mMaNhanvien", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            var kyHoaDonParameter = kyHoaDon != null ?
                new ObjectParameter("kyHoaDon", kyHoaDon) :
                new ObjectParameter("kyHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataGhiChiSo", mMaNhanvienParameter, maTuyenCuocParameter, kyHoaDonParameter);
        }
    
        public virtual ObjectResult<sp_getDataGhichu_Result> sp_getDataGhichu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDataGhichu_Result>("sp_getDataGhichu");
        }
    
        public virtual int sp_getDataGiaBVMT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataGiaBVMT");
        }
    
        public virtual ObjectResult<sp_getDataHoadon_Result> sp_getDataHoadon(string mMaNhanvien, string maTuyenCuoc, string kyHoaDon)
        {
            var mMaNhanvienParameter = mMaNhanvien != null ?
                new ObjectParameter("mMaNhanvien", mMaNhanvien) :
                new ObjectParameter("mMaNhanvien", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            var kyHoaDonParameter = kyHoaDon != null ?
                new ObjectParameter("kyHoaDon", kyHoaDon) :
                new ObjectParameter("kyHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDataHoadon_Result>("sp_getDataHoadon", mMaNhanvienParameter, maTuyenCuocParameter, kyHoaDonParameter);
        }
    
        public virtual int sp_getDataHoadonChitiet(string mMadv, string maTuyenCuoc, string kyHoaDon)
        {
            var mMadvParameter = mMadv != null ?
                new ObjectParameter("mMadv", mMadv) :
                new ObjectParameter("mMadv", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            var kyHoaDonParameter = kyHoaDon != null ?
                new ObjectParameter("kyHoaDon", kyHoaDon) :
                new ObjectParameter("kyHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataHoadonChitiet", mMadvParameter, maTuyenCuocParameter, kyHoaDonParameter);
        }
    
        public virtual ObjectResult<sp_getDataKhachhang_Result> sp_getDataKhachhang(string mMaNhanvien, string maTuyenCuoc)
        {
            var mMaNhanvienParameter = mMaNhanvien != null ?
                new ObjectParameter("mMaNhanvien", mMaNhanvien) :
                new ObjectParameter("mMaNhanvien", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDataKhachhang_Result>("sp_getDataKhachhang", mMaNhanvienParameter, maTuyenCuocParameter);
        }
    
        public virtual ObjectResult<string> sp_getDataKyHoadon(string maNhanVien)
        {
            var maNhanVienParameter = maNhanVien != null ?
                new ObjectParameter("maNhanVien", maNhanVien) :
                new ObjectParameter("maNhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getDataKyHoadon", maNhanVienParameter);
        }
    
        public virtual int sp_getDataPayment(string mMaNhanvien, string maTuyenCuoc, string kyHoaDon)
        {
            var mMaNhanvienParameter = mMaNhanvien != null ?
                new ObjectParameter("mMaNhanvien", mMaNhanvien) :
                new ObjectParameter("mMaNhanvien", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            var kyHoaDonParameter = kyHoaDon != null ?
                new ObjectParameter("kyHoaDon", kyHoaDon) :
                new ObjectParameter("kyHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataPayment", mMaNhanvienParameter, maTuyenCuocParameter, kyHoaDonParameter);
        }
    
        public virtual int sp_getDataPhieuThu(string mMadv, string maTuyenCuoc, string kyHoaDon)
        {
            var mMadvParameter = mMadv != null ?
                new ObjectParameter("mMadv", mMadv) :
                new ObjectParameter("mMadv", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            var kyHoaDonParameter = kyHoaDon != null ?
                new ObjectParameter("kyHoaDon", kyHoaDon) :
                new ObjectParameter("kyHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataPhieuThu", mMadvParameter, maTuyenCuocParameter, kyHoaDonParameter);
        }
    
        public virtual int sp_getDataPhieuThuChitiet(string mMadv, string maTuyenCuoc, string kyHoaDon)
        {
            var mMadvParameter = mMadv != null ?
                new ObjectParameter("mMadv", mMadv) :
                new ObjectParameter("mMadv", typeof(string));
    
            var maTuyenCuocParameter = maTuyenCuoc != null ?
                new ObjectParameter("maTuyenCuoc", maTuyenCuoc) :
                new ObjectParameter("maTuyenCuoc", typeof(string));
    
            var kyHoaDonParameter = kyHoaDon != null ?
                new ObjectParameter("kyHoaDon", kyHoaDon) :
                new ObjectParameter("kyHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataPhieuThuChitiet", mMadvParameter, maTuyenCuocParameter, kyHoaDonParameter);
        }
    
        public virtual int sp_getDataTuyenCuoc(string mMadv, string maNhanVien)
        {
            var mMadvParameter = mMadv != null ?
                new ObjectParameter("mMadv", mMadv) :
                new ObjectParameter("mMadv", typeof(string));
    
            var maNhanVienParameter = maNhanVien != null ?
                new ObjectParameter("maNhanVien", maNhanVien) :
                new ObjectParameter("maNhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getDataTuyenCuoc", mMadvParameter, maNhanVienParameter);
        }
    
        public virtual ObjectResult<sp_getThamSoKiemTra_Result> sp_getThamSoKiemTra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getThamSoKiemTra_Result>("sp_getThamSoKiemTra");
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_PaymentLogon_Result> sp_PaymentLogon(string action, string username, string password)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PaymentLogon_Result>("sp_PaymentLogon", actionParameter, usernameParameter, passwordParameter);
        }
    
        public virtual int sp_ProcessesReceviedMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessesReceviedMessages");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_SaveDataGhiChiSo(string dataxml)
        {
            var dataxmlParameter = dataxml != null ?
                new ObjectParameter("dataxml", dataxml) :
                new ObjectParameter("dataxml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SaveDataGhiChiSo", dataxmlParameter);
        }
    
        public virtual int sp_SaveReceipt(string dataxml)
        {
            var dataxmlParameter = dataxml != null ?
                new ObjectParameter("dataxml", dataxml) :
                new ObjectParameter("dataxml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SaveReceipt", dataxmlParameter);
        }
    
        public virtual int sp_SaveReceiptDetail(string dataxml)
        {
            var dataxmlParameter = dataxml != null ?
                new ObjectParameter("dataxml", dataxml) :
                new ObjectParameter("dataxml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SaveReceiptDetail", dataxmlParameter);
        }
    
        public virtual ObjectResult<sp_SendMessage_Result> sp_SendMessage(string fromServerviceName, string toserviceName, string contractName, string typeMessage, string data)
        {
            var fromServerviceNameParameter = fromServerviceName != null ?
                new ObjectParameter("fromServerviceName", fromServerviceName) :
                new ObjectParameter("fromServerviceName", typeof(string));
    
            var toserviceNameParameter = toserviceName != null ?
                new ObjectParameter("toserviceName", toserviceName) :
                new ObjectParameter("toserviceName", typeof(string));
    
            var contractNameParameter = contractName != null ?
                new ObjectParameter("ContractName", contractName) :
                new ObjectParameter("ContractName", typeof(string));
    
            var typeMessageParameter = typeMessage != null ?
                new ObjectParameter("typeMessage", typeMessage) :
                new ObjectParameter("typeMessage", typeof(string));
    
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SendMessage_Result>("sp_SendMessage", fromServerviceNameParameter, toserviceNameParameter, contractNameParameter, typeMessageParameter, dataParameter);
        }
    
        public virtual ObjectResult<string> sp_updateCus(Nullable<decimal> id_kh)
        {
            var id_khParameter = id_kh.HasValue ?
                new ObjectParameter("id_kh", id_kh) :
                new ObjectParameter("id_kh", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_updateCus", id_khParameter);
        }
    
        public virtual int sp_UpdateCustomers(string dataxml)
        {
            var dataxmlParameter = dataxml != null ?
                new ObjectParameter("dataxml", dataxml) :
                new ObjectParameter("dataxml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateCustomers", dataxmlParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> sp_xmlAdjustInv(Nullable<decimal> id_hd, Nullable<int> type)
        {
            var id_hdParameter = id_hd.HasValue ?
                new ObjectParameter("id_hd", id_hd) :
                new ObjectParameter("id_hd", typeof(decimal));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_xmlAdjustInv", id_hdParameter, typeParameter);
        }
    
        public virtual ObjectResult<string> sp_xmlInvData(string kyGhi, string maLT, string thieu, Nullable<int> sl)
        {
            var kyGhiParameter = kyGhi != null ?
                new ObjectParameter("kyGhi", kyGhi) :
                new ObjectParameter("kyGhi", typeof(string));
    
            var maLTParameter = maLT != null ?
                new ObjectParameter("maLT", maLT) :
                new ObjectParameter("maLT", typeof(string));
    
            var thieuParameter = thieu != null ?
                new ObjectParameter("thieu", thieu) :
                new ObjectParameter("thieu", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_xmlInvData", kyGhiParameter, maLTParameter, thieuParameter, slParameter);
        }
    
        public virtual int TINHCUOC_LOTRINH(string kYCUOC, string mALT, string mANV_TAO)
        {
            var kYCUOCParameter = kYCUOC != null ?
                new ObjectParameter("KYCUOC", kYCUOC) :
                new ObjectParameter("KYCUOC", typeof(string));
    
            var mALTParameter = mALT != null ?
                new ObjectParameter("MALT", mALT) :
                new ObjectParameter("MALT", typeof(string));
    
            var mANV_TAOParameter = mANV_TAO != null ?
                new ObjectParameter("MANV_TAO", mANV_TAO) :
                new ObjectParameter("MANV_TAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TINHCUOC_LOTRINH", kYCUOCParameter, mALTParameter, mANV_TAOParameter);
        }
    
        public virtual int TINHCUOC_LOTRINH_LUU(string kYCUOC, string mALT, string mANV_TAO)
        {
            var kYCUOCParameter = kYCUOC != null ?
                new ObjectParameter("KYCUOC", kYCUOC) :
                new ObjectParameter("KYCUOC", typeof(string));
    
            var mALTParameter = mALT != null ?
                new ObjectParameter("MALT", mALT) :
                new ObjectParameter("MALT", typeof(string));
    
            var mANV_TAOParameter = mANV_TAO != null ?
                new ObjectParameter("MANV_TAO", mANV_TAO) :
                new ObjectParameter("MANV_TAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TINHCUOC_LOTRINH_LUU", kYCUOCParameter, mALTParameter, mANV_TAOParameter);
        }
    
        public virtual int XOA_HOADON_LOTRINH(string kYGHI, string lOTRINH)
        {
            var kYGHIParameter = kYGHI != null ?
                new ObjectParameter("KYGHI", kYGHI) :
                new ObjectParameter("KYGHI", typeof(string));
    
            var lOTRINHParameter = lOTRINH != null ?
                new ObjectParameter("LOTRINH", lOTRINH) :
                new ObjectParameter("LOTRINH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOA_HOADON_LOTRINH", kYGHIParameter, lOTRINHParameter);
        }
    }
}
