//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU
    {
        public Nullable<decimal> tongthanhtoan { get; set; }
        public Nullable<decimal> doanhthu1 { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> luongtieuthu { get; set; }
        public string diengiai { get; set; }
        public Nullable<decimal> tienBVMT { get; set; }
        public string MaLT { get; set; }
        public string tenLT { get; set; }
        public string tenCN { get; set; }
        public string kyghi { get; set; }
        public int nam { get; set; }
        public string maCN_rp { get; set; }
        public Nullable<int> SO_HD { get; set; }
        public Nullable<int> tongKH { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
