//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSHOADON
    {
        public string SO_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<int> luongtieuthu { get; set; }
        public string ten_kyghi { get; set; }
        public decimal tongtien { get; set; }
        public string hoten_KH { get; set; }
        public decimal ID_KH { get; set; }
        public string madanhbo { get; set; }
        public string diachi { get; set; }
        public string maLT { get; set; }
        public decimal ID_HD { get; set; }
        public string trangthai { get; set; }
        public string SOCT { get; set; }
    }
}
