//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaBVMT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaBVMT()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public string ma_giaBVMT { get; set; }
        public string Diengiai { get; set; }
        public decimal giaphi { get; set; }
        public Nullable<decimal> vatphi { get; set; }
        public Nullable<decimal> gia_NThai { get; set; }
        public Nullable<decimal> VAT_NTHAI { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaycapnhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
