//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_LOG
    {
        public decimal id { get; set; }
        public string xml { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string username { get; set; }
    }
}
