//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.CHISONUOCs = new HashSet<CHISONUOC>();
            this.HOADONs = new HashSet<HOADON>();
            this.YEUCAUs = new HashSet<YEUCAU>();
        }
    
        public decimal ID_KH { get; set; }
        public string madanhbo { get; set; }
        public string hoten_KH { get; set; }
        public string diachi { get; set; }
        public string SDT_KH { get; set; }
        public string MST_KH { get; set; }
        public string email { get; set; }
        public long MA_HTTT { get; set; }
        public string SOTK { get; set; }
        public Nullable<decimal> IDNGANHANG { get; set; }
        public Nullable<int> MA_NN { get; set; }
        public int soNK { get; set; }
        public string soHK { get; set; }
        public string ma_giabvmt { get; set; }
        public Nullable<decimal> thuedongho { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string nguoitao { get; set; }
        public Nullable<long> maDH { get; set; }
        public string soseri_DH { get; set; }
        public int trangthai { get; set; }
        public Nullable<System.DateTime> ngaylapdat { get; set; }
        public Nullable<System.DateTime> ngaydoi_DH { get; set; }
        public Nullable<long> MAKC { get; set; }
        public Nullable<System.DateTime> Ngay_Kiemdinh { get; set; }
        public string nguoilapdat { get; set; }
        public string maphuong { get; set; }
        public Nullable<decimal> idKV { get; set; }
        public Nullable<decimal> idduong { get; set; }
        public string sonha { get; set; }
        public string diachithanhtoan { get; set; }
        public bool thanhtoankhaclapdat { get; set; }
        public string maLT { get; set; }
        public int stt_ghi { get; set; }
        public int stt_thu { get; set; }
        public string sohopdong { get; set; }
        public Nullable<System.DateTime> ngaytrangthai { get; set; }
        public string ghichu { get; set; }
        public string maDT { get; set; }
        public Nullable<bool> ischuaxacdinh_NK { get; set; }
        public string bankaccountName { get; set; }
        public string BankName { get; set; }
        public string Banknumber { get; set; }
        public string contactperson { get; set; }
        public string RepresentPerson { get; set; }
        public Nullable<int> STT_ghi_old { get; set; }
        public Nullable<int> STT_thu_old { get; set; }
        public Nullable<bool> isDongBo { get; set; }
        public string NganhNghe { get; set; }
        public string ViTri_LD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHISONUOC> CHISONUOCs { get; set; }
        public virtual DANHMUCTRANGTHAI DANHMUCTRANGTHAI { get; set; }
        public virtual DOITUONGSUDUNG DOITUONGSUDUNG { get; set; }
        public virtual DUONG DUONG { get; set; }
        public virtual GiaBVMT GiaBVMT { get; set; }
        public virtual HINHTHUCTHANHTOAN HINHTHUCTHANHTOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual LOTRINH LOTRINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUCAU> YEUCAUs { get; set; }
    }
}
