//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUVUC
    {
        public decimal idKV { get; set; }
        public string tenKV { get; set; }
        public string maPhuong { get; set; }
    
        public virtual PHUONG PHUONG { get; set; }
    }
}
