//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIYEUCAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIYEUCAU()
        {
            this.DMGHICHUs = new HashSet<DMGHICHU>();
            this.YEUCAUs = new HashSet<YEUCAU>();
        }
    
        public string maloai_yc { get; set; }
        public string tenloai_yc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMGHICHU> DMGHICHUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUCAU> YEUCAUs { get; set; }
    }
}
