//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTRINH()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
            this.LTPhus = new HashSet<LTPhu>();
            this.LTPhus1 = new HashSet<LTPhu>();
            this.LTPhus2 = new HashSet<LTPhu>();
        }
    
        public string maLT { get; set; }
        public string tenLT { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngay_BD { get; set; }
        public Nullable<int> STT_danhbo { get; set; }
        public string maCN { get; set; }
        public Nullable<int> ID_NV_ghi { get; set; }
        public Nullable<int> ID_NV_thu { get; set; }
        public string STT { get; set; }
        public string maCN_rp { get; set; }
        public string DAU_DANHBO { get; set; }
    
        public virtual CHINHANH CHINHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTPhu> LTPhus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTPhu> LTPhus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTPhu> LTPhus2 { get; set; }
    }
}
