//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAU_HD
    {
        public string ky_hieu_HD { get; set; }
        public string mau_HD1 { get; set; }
        public Nullable<decimal> sohd { get; set; }
        public Nullable<decimal> somax { get; set; }
    }
}
