//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_LNV
    {
        public int id { get; set; }
        public int NV_ID { get; set; }
        public int ID_LoaiNV { get; set; }
    
        public virtual LOAINHANVIEN LOAINHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
