//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.GiaoPhieux = new HashSet<GiaoPhieu>();
            this.NHANVIEN_LNV = new HashSet<NHANVIEN_LNV>();
        }
    
        public int NV_ID { get; set; }
        public string maNV { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string quoctich { get; set; }
        public string soCMND { get; set; }
        public Nullable<System.DateTime> ngaycap { get; set; }
        public string noicap { get; set; }
        public string diachithuongtru { get; set; }
        public string diachitamtru { get; set; }
        public string masothue { get; set; }
        public string SDT_NV { get; set; }
        public string SDT_codinh { get; set; }
        public Nullable<int> ID_LoaiNV { get; set; }
        public string maPB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoPhieu> GiaoPhieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_LNV> NHANVIEN_LNV { get; set; }
    }
}
