//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGBAN
    {
        public string maPB { get; set; }
        public string tenPB { get; set; }
        public string mota { get; set; }
        public string maCN { get; set; }
    
        public virtual CHINHANH CHINHANH { get; set; }
        public virtual CHINHANH CHINHANH1 { get; set; }
        public virtual CHINHANH CHINHANH2 { get; set; }
    }
}
