//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN_MENU
    {
        public decimal id { get; set; }
        public Nullable<decimal> quyen_id { get; set; }
        public string ten_menu { get; set; }
    
        public virtual QUYEN QUYEN { get; set; }
    }
}
