//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASSPRO_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongkedoanhthu
    {
        public Nullable<long> STT { get; set; }
        public string maLT { get; set; }
        public string tenlt { get; set; }
        public int tonghdthu { get; set; }
        public string ten_kyghi { get; set; }
        public Nullable<decimal> tongthanhtoan { get; set; }
        public string kyghi { get; set; }
        public decimal tongthu { get; set; }
        public int tonghd { get; set; }
        public Nullable<decimal> tongno { get; set; }
        public double tyle { get; set; }
        public Nullable<int> tonghdchuathu { get; set; }
        public Nullable<int> sl { get; set; }
    }
}
