//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGGIA_DM_DB
    {
        public decimal dinhmuc_id { get; set; }
        public decimal dongia { get; set; }
        public decimal dongia0V { get; set; }
        public decimal tutyle { get; set; }
        public decimal dentyle { get; set; }
        public string diengiai { get; set; }
        public decimal id_kh { get; set; }
    }
}
