//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_KHACHHANG
    {
        public decimal IDBD { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public string madanhbo { get; set; }
        public string hoten_KH { get; set; }
        public string diachi { get; set; }
        public string SDT_KH { get; set; }
        public string MST_KH { get; set; }
        public string email { get; set; }
        public Nullable<long> MA_HTTT { get; set; }
        public Nullable<int> MA_NN { get; set; }
        public Nullable<int> soNK { get; set; }
        public string soHK { get; set; }
        public string ma_giabvmt { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<long> maDH { get; set; }
        public string soseri_DH { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<System.DateTime> ngaylapdat { get; set; }
        public Nullable<System.DateTime> ngaydoi_DH { get; set; }
        public Nullable<long> MAKC { get; set; }
        public Nullable<System.DateTime> Ngay_Kiemdinh { get; set; }
        public string nguoilapdat { get; set; }
        public string maphuong { get; set; }
        public Nullable<decimal> idKV { get; set; }
        public Nullable<decimal> idduong { get; set; }
        public string sonha { get; set; }
        public string diachithanhtoan { get; set; }
        public Nullable<bool> thanhtoankhaclapdat { get; set; }
        public string maLT { get; set; }
        public Nullable<int> stt_ghi { get; set; }
        public Nullable<int> stt_thu { get; set; }
        public string sohopdong { get; set; }
        public Nullable<System.DateTime> ngaytrangthai { get; set; }
        public string ghichu { get; set; }
        public string maDT { get; set; }
        public Nullable<bool> ischuaxacdinh_NK { get; set; }
        public string bankaccountName { get; set; }
        public string BankName { get; set; }
        public string Banknumber { get; set; }
        public string contactperson { get; set; }
        public string RepresentPerson { get; set; }
        public string hieuDH { get; set; }
        public string kichcoDH { get; set; }
        public Nullable<int> nvid { get; set; }
    }
}
