//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGTU_CHISONUOC
    {
        public decimal ID_CT { get; set; }
        public decimal ID_Chisonuoc { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public string trangthai { get; set; }
    }
}
