//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGNGANKH
    {
        public decimal DANGNGANKH_ID { get; set; }
        public Nullable<decimal> ID_HD { get; set; }
        public Nullable<decimal> NV_ID { get; set; }
        public Nullable<System.DateTime> NGAYDANGNGAN_NV { get; set; }
        public Nullable<decimal> NV_ID_BLL { get; set; }
        public Nullable<System.DateTime> NGAY_BILLING { get; set; }
        public Nullable<bool> IsDangNgan { get; set; }
        public Nullable<decimal> GachnoKHID { get; set; }
        public Nullable<decimal> IDCT { get; set; }
    
        public virtual GACHNOKH GACHNOKH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
