//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuChinhTT
    {
        public decimal IDHD { get; set; }
        public Nullable<double> DANHBO { get; set; }
        public string MST { get; set; }
        public Nullable<double> KY { get; set; }
    }
}
