//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_BANGGIA
    {
        public decimal dinhmuc_id { get; set; }
        public decimal dongia { get; set; }
        public decimal dongia0V { get; set; }
        public decimal tum3 { get; set; }
        public decimal denm3 { get; set; }
        public string diengiai { get; set; }
        public string maDT { get; set; }
    
        public virtual DM_DOITUONGSUDUNG DM_DOITUONGSUDUNG { get; set; }
    }
}
