//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DOITUONGSUDUNG
    {
        public DM_DOITUONGSUDUNG()
        {
            this.DM_BANGGIA = new HashSet<DM_BANGGIA>();
        }
    
        public string maDT { get; set; }
        public string tenDT { get; set; }
        public string ma_giaBVMT { get; set; }
        public Nullable<bool> theoNK { get; set; }
        public Nullable<int> stt { get; set; }
        public string MaLoaiHD { get; set; }
    
        public virtual ICollection<DM_BANGGIA> DM_BANGGIA { get; set; }
    }
}
