//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GHICHU
    {
        public DM_GHICHU()
        {
            this.CHISONUOCs = new HashSet<CHISONUOC>();
        }
    
        public int ghichuid { get; set; }
        public string noidung { get; set; }
        public string maloai_yc { get; set; }
    
        public virtual ICollection<CHISONUOC> CHISONUOCs { get; set; }
        public virtual DM_LOAIYEUCAU DM_LOAIYEUCAU { get; set; }
    }
}
