//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GIABIEU
    {
        public string MA { get; set; }
        public string TEN { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> THUTU { get; set; }
        public string MACU { get; set; }
        public Nullable<bool> HIENTHI { get; set; }
        public string MAHIENTHI { get; set; }
    }
}
