//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HINHTHUCTHANHTOAN
    {
        public DM_HINHTHUCTHANHTOAN()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
            this.KHACHHANG_TDC = new HashSet<KHACHHANG_TDC>();
        }
    
        public long maHTTT { get; set; }
        public string tenHTTT { get; set; }
        public string tentat { get; set; }
    
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
        public virtual ICollection<KHACHHANG_TDC> KHACHHANG_TDC { get; set; }
    }
}
