//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHUVUC
    {
        public DM_KHUVUC()
        {
            this.KHACHHANG_TDC = new HashSet<KHACHHANG_TDC>();
        }
    
        public decimal idKV { get; set; }
        public string tenKV { get; set; }
        public string maPhuong { get; set; }
    
        public virtual DM_PHUONG DM_PHUONG { get; set; }
        public virtual ICollection<KHACHHANG_TDC> KHACHHANG_TDC { get; set; }
    }
}
