//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LYDO
    {
        public DM_LYDO()
        {
            this.YEUCAUs = new HashSet<YEUCAU>();
        }
    
        public int id_lydo { get; set; }
        public string ten_lydo { get; set; }
    
        public virtual ICollection<YEUCAU> YEUCAUs { get; set; }
    }
}
