//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAIYEUCAU
    {
        public DM_LOAIYEUCAU()
        {
            this.DM_GHICHU = new HashSet<DM_GHICHU>();
            this.YEUCAUs = new HashSet<YEUCAU>();
        }
    
        public string maloai_yc { get; set; }
        public string tenloai_yc { get; set; }
    
        public virtual ICollection<DM_GHICHU> DM_GHICHU { get; set; }
        public virtual ICollection<YEUCAU> YEUCAUs { get; set; }
    }
}
