//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAINHANVIEN
    {
        public DM_LOAINHANVIEN()
        {
            this.NHANVIEN_LNV = new HashSet<NHANVIEN_LNV>();
        }
    
        public int ID_LoaiNV { get; set; }
        public string Tenloai { get; set; }
    
        public virtual ICollection<NHANVIEN_LNV> NHANVIEN_LNV { get; set; }
    }
}
