//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NGANHANG
    {
        public DM_NGANHANG()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public decimal NGANHANG_ID { get; set; }
        public string MA_NGANHANG { get; set; }
        public string TENNGANHANG { get; set; }
        public string LOAI { get; set; }
        public string MADV { get; set; }
    
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
