//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_QUYEN
    {
        public DM_QUYEN()
        {
            this.NGUOIDUNG_QUYEN = new HashSet<NGUOIDUNG_QUYEN>();
            this.QUYEN_MENU = new HashSet<QUYEN_MENU>();
        }
    
        public decimal quyen_id { get; set; }
        public string tenquyen { get; set; }
    
        public virtual ICollection<NGUOIDUNG_QUYEN> NGUOIDUNG_QUYEN { get; set; }
        public virtual ICollection<QUYEN_MENU> QUYEN_MENU { get; set; }
    }
}
