//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TINH
    {
        public DM_TINH()
        {
            this.DM_QUAN = new HashSet<DM_QUAN>();
        }
    
        public string maTinh { get; set; }
        public string tenTinh { get; set; }
    
        public virtual ICollection<DM_QUAN> DM_QUAN { get; set; }
    }
}
