//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSHoaDonThu
    {
        public Nullable<System.DateTime> ngay_thu_tien { get; set; }
        public string SO_HOADON_BLL { get; set; }
        public Nullable<int> nam { get; set; }
        public string ten_kyghi { get; set; }
        public string TENDOT { get; set; }
        public string SO_HD { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public string DANHBO { get; set; }
        public string hoten { get; set; }
        public string diachi { get; set; }
        public decimal ID_HD { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public decimal NV_ID { get; set; }
    }
}
