//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GACHNOCK
    {
        public GACHNOCK()
        {
            this.DANGNGANCKs = new HashSet<DANGNGANCK>();
        }
    
        public decimal GachnoCKID { get; set; }
        public Nullable<decimal> IDHD { get; set; }
        public Nullable<decimal> IDKH { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<System.DateTime> Ngaythanhtoan { get; set; }
        public Nullable<int> NVID { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<decimal> NganhangID { get; set; }
        public Nullable<decimal> IDCT { get; set; }
    
        public virtual CHUNGTU CHUNGTU { get; set; }
        public virtual ICollection<DANGNGANCK> DANGNGANCKs { get; set; }
    }
}
