//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GACHNOLOI
    {
        public decimal GACHNOLOI_ID { get; set; }
        public decimal ID_HD { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public Nullable<decimal> NAM_ID { get; set; }
        public string ID_KYGHI { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public string MALT { get; set; }
        public Nullable<decimal> NV_ID_NOP { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<decimal> TIENTHUE_GTGT { get; set; }
        public Nullable<decimal> TONGTIENBVMT { get; set; }
        public Nullable<decimal> TONGTHANHTOAN { get; set; }
        public string MALOAI { get; set; }
        public string SOHD { get; set; }
        public string KYHIEU { get; set; }
        public string MAUSO { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<System.DateTime> NGAYDONGBO { get; set; }
        public string PRODUCTS { get; set; }
        public Nullable<decimal> USER_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public Nullable<decimal> USER_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
