//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoPhieu
    {
        public decimal id { get; set; }
        public Nullable<decimal> id_yeucau { get; set; }
        public Nullable<decimal> id_nv { get; set; }
    }
}
