//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_KHODOI
    {
        public decimal ID_NO { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public Nullable<decimal> ID_HD { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> NGUOICHUYEN { get; set; }
        public Nullable<System.DateTime> NGAYCHUYEN { get; set; }
        public Nullable<System.DateTime> NGAYXOANO { get; set; }
        public Nullable<int> NGUOIXOANO { get; set; }
        public Nullable<System.DateTime> NGAYDANGNGAN { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<bool> ISDANGNGAN { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
        public string NGUOITHANHTOAN { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
    }
}
