//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONDIEUCHINH
    {
        public decimal IDHD_DC { get; set; }
        public Nullable<decimal> IDHD { get; set; }
        public string kyghi { get; set; }
        public Nullable<decimal> ID_KH { get; set; }
        public string MST { get; set; }
        public string MADT { get; set; }
        public Nullable<int> soNK { get; set; }
        public Nullable<long> ma_HTTT { get; set; }
        public string MaLT { get; set; }
        public string hoten { get; set; }
        public Nullable<bool> IsInHD { get; set; }
        public string sohopdong { get; set; }
        public Nullable<int> DMKH { get; set; }
        public string MTT { get; set; }
        public string MGB { get; set; }
        public string DANHBO { get; set; }
        public string SOPHATHANH { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public Nullable<int> CSMoi { get; set; }
        public Nullable<int> CSCu { get; set; }
        public Nullable<int> m3tieuthu { get; set; }
        public Nullable<int> m3BVMT { get; set; }
        public Nullable<decimal> dongiaBVMT { get; set; }
        public Nullable<decimal> tienBVMT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> tienvat { get; set; }
        public Nullable<decimal> tongtien0VAT { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public string MAU_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string SO_HD { get; set; }
        public Nullable<System.DateTime> ArisingDate { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<bool> gachno { get; set; }
        public Nullable<decimal> trangthai_id { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public Nullable<decimal> user_create { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<decimal> LoaiHD_ID { get; set; }
        public Nullable<int> ischeck { get; set; }
        public Nullable<decimal> hoadonTDC_id { get; set; }
        public string cuonGCS { get; set; }
        public Nullable<int> STT_thu { get; set; }
        public string diachihoadon { get; set; }
    }
}
