//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_HUY
    {
        public decimal id_hd { get; set; }
        public Nullable<decimal> id_kh { get; set; }
        public Nullable<decimal> tienbvmt { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<System.DateTime> ngayhuy { get; set; }
        public string nguoihuy { get; set; }
    }
}
