//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA_DANGNGAN
    {
        public long STT { get; set; }
        public bool TRANG_THAI { get; set; }
        public System.DateTime NGAY_DANG_NGAN { get; set; }
        public System.DateTime NGAY_THUC_HIEN { get; set; }
        public string NGUOI_THUC_HIEN { get; set; }
    }
}
