//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string Action { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
