//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG_CHUCNANG
    {
        public decimal PID { get; set; }
        public string PAGE_NAME { get; set; }
        public string PAGE_URL { get; set; }
        public string FUNCTION { get; set; }
        public decimal NV_ID { get; set; }
    }
}
