//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_HOADON
    {
        public decimal ID { get; set; }
        public Nullable<decimal> NV_ID { get; set; }
        public string MAND { get; set; }
        public string CUON_GCS { get; set; }
        public Nullable<int> TuLT { get; set; }
        public Nullable<int> DenLT { get; set; }
        public string GIOBD { get; set; }
        public string GIOKT { get; set; }
        public Nullable<bool> T7 { get; set; }
        public Nullable<bool> CN { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<decimal> USER_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public Nullable<decimal> USER_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
    
        public virtual DM_DOT DM_DOT { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
        public virtual NHANVIEN NHANVIEN2 { get; set; }
    }
}
