//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuthu_kh
    {
        public string GUID { get; set; }
        public string FKEY { get; set; }
        public string so_pt { get; set; }
        public string ky_hieu_pt { get; set; }
        public string so_hd { get; set; }
        public string ky_hieu_hd { get; set; }
        public string seri { get; set; }
        public string ma_kh { get; set; }
        public string account { get; set; }
        public string so_hdg { get; set; }
        public string ten_kh { get; set; }
        public string dia_chi { get; set; }
        public string tel_phone { get; set; }
        public string email { get; set; }
        public string ma_thue { get; set; }
        public string HTTT { get; set; }
        public Nullable<System.DateTime> ngay_thu_tien { get; set; }
        public Nullable<System.DateTime> ngay_phat_hanh { get; set; }
        public string so_bo { get; set; }
        public string loai_kh { get; set; }
        public string gia_nk { get; set; }
        public Nullable<decimal> cs_cu { get; set; }
        public Nullable<decimal> cs_moi { get; set; }
        public Nullable<decimal> m3tt { get; set; }
        public Nullable<decimal> tienluubo { get; set; }
        public Nullable<decimal> tienpbvmt { get; set; }
        public Nullable<decimal> tienpnt { get; set; }
        public Nullable<decimal> tien_hang { get; set; }
        public Nullable<decimal> tien_giam_tru { get; set; }
        public Nullable<decimal> thue_gtgt { get; set; }
        public Nullable<decimal> tien_thue { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public Nullable<decimal> tong_thu { get; set; }
        public Nullable<decimal> thang_ps { get; set; }
        public Nullable<int> Checks { get; set; }
        public Nullable<System.DateTime> ngay_thuc_hien { get; set; }
        public string ma_dv { get; set; }
        public string ma_tuyen_cuoc { get; set; }
        public string nv_thu { get; set; }
        public Nullable<decimal> nv_id { get; set; }
        public Nullable<double> locationX { get; set; }
        public Nullable<double> locationY { get; set; }
        public string malt { get; set; }
        public Nullable<int> MGB { get; set; }
        public Nullable<int> DMKH { get; set; }
        public Nullable<int> MTT { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public string SOHD_BLL { get; set; }
        public Nullable<decimal> dot_id { get; set; }
        public string ghichu_dc { get; set; }
    }
}
