//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishedInvoices2024
    {
        public int STT { get; set; }
        public string KEY { get; set; }
        public decimal IDKH { get; set; }
        public Nullable<int> NAM { get; set; }
        public string KYHD { get; set; }
        public Nullable<decimal> SOPHIEU { get; set; }
        public string SO_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string MAU_HD { get; set; }
        public string SODB { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string MST { get; set; }
        public string GIANK { get; set; }
        public Nullable<int> CSCU { get; set; }
        public Nullable<int> CSMOI { get; set; }
        public Nullable<decimal> M3TT { get; set; }
        public string PRODUCTS { get; set; }
        public Nullable<decimal> CONGTHANHTIEN { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> TIENVAT { get; set; }
        public Nullable<decimal> TIENLUUBO { get; set; }
        public Nullable<decimal> PBVMT4M3 { get; set; }
        public Nullable<decimal> TIENPBVMT { get; set; }
        public Nullable<decimal> PNT4M3 { get; set; }
        public Nullable<decimal> TIENPNT { get; set; }
        public Nullable<decimal> TONGCONG { get; set; }
        public string MAHTTT { get; set; }
        public string LOAI_PH { get; set; }
        public Nullable<System.DateTime> NGAYINHD { get; set; }
        public string CHECKS { get; set; }
        public string GACH_NO { get; set; }
        public string MAKV { get; set; }
        public string STATUS { get; set; }
        public string ERRORS { get; set; }
        public Nullable<System.DateTime> NGAY_THUC_HIEN { get; set; }
        public Nullable<int> thang_ps { get; set; }
        public string ma_tuyen_cuoc { get; set; }
        public string valuesKeySearch { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public Nullable<int> DMKH { get; set; }
        public string MTT { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public string SO_PHATHANH { get; set; }
        public Nullable<int> MGB { get; set; }
        public Nullable<decimal> NVID_THU { get; set; }
        public Nullable<bool> HD_TON { get; set; }
        public Nullable<decimal> FKEY_DC { get; set; }
        public string GHICHU_DC { get; set; }
        public Nullable<bool> isKhodoi { get; set; }
        public string CUON_GCS { get; set; }
        public Nullable<int> CUON_STT { get; set; }
        public Nullable<decimal> IDNhanvienHD { get; set; }
        public Nullable<decimal> IDHD { get; set; }
        public string NVThu { get; set; }
        public Nullable<System.DateTime> Ngaythutienapp { get; set; }
    }
}
