//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN_SERVICE
    {
        public int TK_ID { get; set; }
        public string acc_admin { get; set; }
        public string pass_admin { get; set; }
        public string acc_service { get; set; }
        public string pass_service { get; set; }
    }
}
