//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRANSACTIONS_LOG
    {
        public long PID { get; set; }
        public string LOG_TYPE { get; set; }
        public string UID { get; set; }
        public string TRANS_NO { get; set; }
        public string NOTES { get; set; }
        public string TAG1 { get; set; }
        public string TAG2 { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
