//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUTON_HD
    {
        public decimal TONTHU_ID { get; set; }
        public Nullable<decimal> NV_ID { get; set; }
        public Nullable<decimal> ID_HD { get; set; }
        public Nullable<System.DateTime> ngaythuchien { get; set; }
        public Nullable<bool> isHDTon { get; set; }
    }
}
