//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonDochub
    {
        public decimal ID { get; set; }
        public string hoten_KH { get; set; }
        public string danhbo { get; set; }
        public string malt { get; set; }
        public string diachihoadon { get; set; }
        public string kyghi { get; set; }
        public Nullable<decimal> tongtien { get; set; }
    }
}
