//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongDuLieuDieuChinh
    {
        public decimal DieuChinhID { get; set; }
        public decimal KhachHangID { get; set; }
        public string KyHoaDon { get; set; }
        public decimal HoaDonID { get; set; }
        public Nullable<decimal> TienNuocDC { get; set; }
        public Nullable<decimal> TienThueDC { get; set; }
        public Nullable<decimal> TienPhiBVMTDC { get; set; }
        public Nullable<decimal> TienPhiNTDC { get; set; }
        public Nullable<decimal> ThuePhiNTDC { get; set; }
        public Nullable<decimal> TongTienDC { get; set; }
    }
}
