//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWDANHSACHTHU_APP
    {
        public Nullable<decimal> FKEY { get; set; }
        public Nullable<decimal> tong_thu { get; set; }
        public decimal NV_ID { get; set; }
        public string hoten { get; set; }
        public Nullable<int> Checks { get; set; }
        public Nullable<System.DateTime> ngay_thuc_hien { get; set; }
        public string manv { get; set; }
        public string somay { get; set; }
        public Nullable<decimal> TO_ID { get; set; }
    }
}
