//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWDANHSACHKHACHHANG
    {
        public decimal ID_KH { get; set; }
        public string madanhbo { get; set; }
        public string hoten_KH { get; set; }
        public string sonha { get; set; }
        public string diachi { get; set; }
        public string tenPhuong { get; set; }
        public string tenQuan { get; set; }
        public string timkiem { get; set; }
        public string MST_KH { get; set; }
        public string tenTT { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string maLT { get; set; }
        public string nguoitao { get; set; }
        public string maquan { get; set; }
        public string maphuong { get; set; }
        public string maDT { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<decimal> dotid { get; set; }
        public string SDT_KH { get; set; }
        public Nullable<bool> isingiaybao { get; set; }
        public string trangthaiKH { get; set; }
    }
}
