//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongNo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DSKHACHHANG_HOADON
    {
        public Nullable<decimal> ID_KH { get; set; }
        public string kyghi { get; set; }
        public Nullable<int> nam { get; set; }
        public string hoten { get; set; }
        public string sonha { get; set; }
        public string diachi { get; set; }
        public string MST { get; set; }
        public string MADT { get; set; }
        public string MaLT { get; set; }
        public Nullable<bool> IsInHD { get; set; }
        public string MGB { get; set; }
        public string DANHBO { get; set; }
        public Nullable<decimal> DOT_ID { get; set; }
        public string quan { get; set; }
        public string phuong { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<decimal> LoaiHD_ID { get; set; }
        public string timkiem { get; set; }
        public string tenPhuong { get; set; }
        public string tenQuan { get; set; }
    }
}
