//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QLCongNo.AccountTDC {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccountSoap", Namespace="http://TDService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Account : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AccountLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountChangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountUpdate_PassOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceExecuteQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceExecuteCommandOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceExecuteCommandByParamOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AppStartingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AccountLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AccountCheckingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AccountNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AccountNew_2OperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AccountUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceOTP_SendOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceOTP_AuthenOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceOTP_SendTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AccountLostPassOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_AccountLostPassUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSKH_SendSMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Account() {
            this.Url = global::QLCongNo.Properties.Settings.Default.QLCongNo_AccountTDC_Account;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AccountLoginCompletedEventHandler AccountLoginCompleted;
        
        /// <remarks/>
        public event AccountRegisterCompletedEventHandler AccountRegisterCompleted;
        
        /// <remarks/>
        public event AccountUpdateCompletedEventHandler AccountUpdateCompleted;
        
        /// <remarks/>
        public event AccountChangeCompletedEventHandler AccountChangeCompleted;
        
        /// <remarks/>
        public event AccountUpdate_PassCompletedEventHandler AccountUpdate_PassCompleted;
        
        /// <remarks/>
        public event ServiceExecuteQueryCompletedEventHandler ServiceExecuteQueryCompleted;
        
        /// <remarks/>
        public event ServiceExecuteCommandCompletedEventHandler ServiceExecuteCommandCompleted;
        
        /// <remarks/>
        public event ServiceExecuteCommandByParamCompletedEventHandler ServiceExecuteCommandByParamCompleted;
        
        /// <remarks/>
        public event CSKH_AppStartingCompletedEventHandler CSKH_AppStartingCompleted;
        
        /// <remarks/>
        public event CSKH_AccountLoginCompletedEventHandler CSKH_AccountLoginCompleted;
        
        /// <remarks/>
        public event CSKH_AccountCheckingCompletedEventHandler CSKH_AccountCheckingCompleted;
        
        /// <remarks/>
        public event CSKH_AccountNewCompletedEventHandler CSKH_AccountNewCompleted;
        
        /// <remarks/>
        public event CSKH_AccountNew_2CompletedEventHandler CSKH_AccountNew_2Completed;
        
        /// <remarks/>
        public event CSKH_AccountUpdateCompletedEventHandler CSKH_AccountUpdateCompleted;
        
        /// <remarks/>
        public event ServiceOTP_SendCompletedEventHandler ServiceOTP_SendCompleted;
        
        /// <remarks/>
        public event ServiceOTP_AuthenCompletedEventHandler ServiceOTP_AuthenCompleted;
        
        /// <remarks/>
        public event ServiceOTP_SendTestCompletedEventHandler ServiceOTP_SendTestCompleted;
        
        /// <remarks/>
        public event CSKH_AccountLostPassCompletedEventHandler CSKH_AccountLostPassCompleted;
        
        /// <remarks/>
        public event CSKH_AccountLostPassUpdateCompletedEventHandler CSKH_AccountLostPassUpdateCompleted;
        
        /// <remarks/>
        public event CSKH_SendSMSCompletedEventHandler CSKH_SendSMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/AccountLogin", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AccountLogin(string pServiceID, string pServicePass, string pProjectID, string pAccountID, string pAccountPassword, string pDevice, string pTag) {
            object[] results = this.Invoke("AccountLogin", new object[] {
                        pServiceID,
                        pServicePass,
                        pProjectID,
                        pAccountID,
                        pAccountPassword,
                        pDevice,
                        pTag});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AccountLoginAsync(string pServiceID, string pServicePass, string pProjectID, string pAccountID, string pAccountPassword, string pDevice, string pTag) {
            this.AccountLoginAsync(pServiceID, pServicePass, pProjectID, pAccountID, pAccountPassword, pDevice, pTag, null);
        }
        
        /// <remarks/>
        public void AccountLoginAsync(string pServiceID, string pServicePass, string pProjectID, string pAccountID, string pAccountPassword, string pDevice, string pTag, object userState) {
            if ((this.AccountLoginOperationCompleted == null)) {
                this.AccountLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountLoginOperationCompleted);
            }
            this.InvokeAsync("AccountLogin", new object[] {
                        pServiceID,
                        pServicePass,
                        pProjectID,
                        pAccountID,
                        pAccountPassword,
                        pDevice,
                        pTag}, this.AccountLoginOperationCompleted, userState);
        }
        
        private void OnAccountLoginOperationCompleted(object arg) {
            if ((this.AccountLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountLoginCompleted(this, new AccountLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/AccountRegister", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] AccountRegister(string pLoginName, string pLoginPass, string pAccountID, System.Data.DataTable pAccountParam, string pAccountEmail, bool pIsSendMail, string pDevice, string pTag) {
            object[] results = this.Invoke("AccountRegister", new object[] {
                        pLoginName,
                        pLoginPass,
                        pAccountID,
                        pAccountParam,
                        pAccountEmail,
                        pIsSendMail,
                        pDevice,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void AccountRegisterAsync(string pLoginName, string pLoginPass, string pAccountID, System.Data.DataTable pAccountParam, string pAccountEmail, bool pIsSendMail, string pDevice, string pTag) {
            this.AccountRegisterAsync(pLoginName, pLoginPass, pAccountID, pAccountParam, pAccountEmail, pIsSendMail, pDevice, pTag, null);
        }
        
        /// <remarks/>
        public void AccountRegisterAsync(string pLoginName, string pLoginPass, string pAccountID, System.Data.DataTable pAccountParam, string pAccountEmail, bool pIsSendMail, string pDevice, string pTag, object userState) {
            if ((this.AccountRegisterOperationCompleted == null)) {
                this.AccountRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountRegisterOperationCompleted);
            }
            this.InvokeAsync("AccountRegister", new object[] {
                        pLoginName,
                        pLoginPass,
                        pAccountID,
                        pAccountParam,
                        pAccountEmail,
                        pIsSendMail,
                        pDevice,
                        pTag}, this.AccountRegisterOperationCompleted, userState);
        }
        
        private void OnAccountRegisterOperationCompleted(object arg) {
            if ((this.AccountRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountRegisterCompleted(this, new AccountRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/AccountUpdate", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] AccountUpdate(string pLoginName, string pLoginPass, string pProjectID, string pAccountID, string pFormName, string pFunctionName, string pFunctionType, string pContent, string pAccountPassword, System.Data.DataTable pAccountParam, bool pIsAdmin, string pDevice, string pTag) {
            object[] results = this.Invoke("AccountUpdate", new object[] {
                        pLoginName,
                        pLoginPass,
                        pProjectID,
                        pAccountID,
                        pFormName,
                        pFunctionName,
                        pFunctionType,
                        pContent,
                        pAccountPassword,
                        pAccountParam,
                        pIsAdmin,
                        pDevice,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void AccountUpdateAsync(string pLoginName, string pLoginPass, string pProjectID, string pAccountID, string pFormName, string pFunctionName, string pFunctionType, string pContent, string pAccountPassword, System.Data.DataTable pAccountParam, bool pIsAdmin, string pDevice, string pTag) {
            this.AccountUpdateAsync(pLoginName, pLoginPass, pProjectID, pAccountID, pFormName, pFunctionName, pFunctionType, pContent, pAccountPassword, pAccountParam, pIsAdmin, pDevice, pTag, null);
        }
        
        /// <remarks/>
        public void AccountUpdateAsync(string pLoginName, string pLoginPass, string pProjectID, string pAccountID, string pFormName, string pFunctionName, string pFunctionType, string pContent, string pAccountPassword, System.Data.DataTable pAccountParam, bool pIsAdmin, string pDevice, string pTag, object userState) {
            if ((this.AccountUpdateOperationCompleted == null)) {
                this.AccountUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountUpdateOperationCompleted);
            }
            this.InvokeAsync("AccountUpdate", new object[] {
                        pLoginName,
                        pLoginPass,
                        pProjectID,
                        pAccountID,
                        pFormName,
                        pFunctionName,
                        pFunctionType,
                        pContent,
                        pAccountPassword,
                        pAccountParam,
                        pIsAdmin,
                        pDevice,
                        pTag}, this.AccountUpdateOperationCompleted, userState);
        }
        
        private void OnAccountUpdateOperationCompleted(object arg) {
            if ((this.AccountUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountUpdateCompleted(this, new AccountUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/AccountChange", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] AccountChange(string pServiceID, string pServicePass, string pProjectID, string pAccountID, string pType, string[] pData, string pDevice, string pTag) {
            object[] results = this.Invoke("AccountChange", new object[] {
                        pServiceID,
                        pServicePass,
                        pProjectID,
                        pAccountID,
                        pType,
                        pData,
                        pDevice,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void AccountChangeAsync(string pServiceID, string pServicePass, string pProjectID, string pAccountID, string pType, string[] pData, string pDevice, string pTag) {
            this.AccountChangeAsync(pServiceID, pServicePass, pProjectID, pAccountID, pType, pData, pDevice, pTag, null);
        }
        
        /// <remarks/>
        public void AccountChangeAsync(string pServiceID, string pServicePass, string pProjectID, string pAccountID, string pType, string[] pData, string pDevice, string pTag, object userState) {
            if ((this.AccountChangeOperationCompleted == null)) {
                this.AccountChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountChangeOperationCompleted);
            }
            this.InvokeAsync("AccountChange", new object[] {
                        pServiceID,
                        pServicePass,
                        pProjectID,
                        pAccountID,
                        pType,
                        pData,
                        pDevice,
                        pTag}, this.AccountChangeOperationCompleted, userState);
        }
        
        private void OnAccountChangeOperationCompleted(object arg) {
            if ((this.AccountChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountChangeCompleted(this, new AccountChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/AccountUpdate_Pass", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] AccountUpdate_Pass(string pServiceID, string pServicePass, string pAccountID, string[] pPassInfo, string pDevice, string pTag) {
            object[] results = this.Invoke("AccountUpdate_Pass", new object[] {
                        pServiceID,
                        pServicePass,
                        pAccountID,
                        pPassInfo,
                        pDevice,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void AccountUpdate_PassAsync(string pServiceID, string pServicePass, string pAccountID, string[] pPassInfo, string pDevice, string pTag) {
            this.AccountUpdate_PassAsync(pServiceID, pServicePass, pAccountID, pPassInfo, pDevice, pTag, null);
        }
        
        /// <remarks/>
        public void AccountUpdate_PassAsync(string pServiceID, string pServicePass, string pAccountID, string[] pPassInfo, string pDevice, string pTag, object userState) {
            if ((this.AccountUpdate_PassOperationCompleted == null)) {
                this.AccountUpdate_PassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountUpdate_PassOperationCompleted);
            }
            this.InvokeAsync("AccountUpdate_Pass", new object[] {
                        pServiceID,
                        pServicePass,
                        pAccountID,
                        pPassInfo,
                        pDevice,
                        pTag}, this.AccountUpdate_PassOperationCompleted, userState);
        }
        
        private void OnAccountUpdate_PassOperationCompleted(object arg) {
            if ((this.AccountUpdate_PassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountUpdate_PassCompleted(this, new AccountUpdate_PassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/ServiceExecuteQuery", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ServiceExecuteQuery(string pLoginName, string pLoginPass, string pSqlCommand, string pDatabase) {
            object[] results = this.Invoke("ServiceExecuteQuery", new object[] {
                        pLoginName,
                        pLoginPass,
                        pSqlCommand,
                        pDatabase});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ServiceExecuteQueryAsync(string pLoginName, string pLoginPass, string pSqlCommand, string pDatabase) {
            this.ServiceExecuteQueryAsync(pLoginName, pLoginPass, pSqlCommand, pDatabase, null);
        }
        
        /// <remarks/>
        public void ServiceExecuteQueryAsync(string pLoginName, string pLoginPass, string pSqlCommand, string pDatabase, object userState) {
            if ((this.ServiceExecuteQueryOperationCompleted == null)) {
                this.ServiceExecuteQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceExecuteQueryOperationCompleted);
            }
            this.InvokeAsync("ServiceExecuteQuery", new object[] {
                        pLoginName,
                        pLoginPass,
                        pSqlCommand,
                        pDatabase}, this.ServiceExecuteQueryOperationCompleted, userState);
        }
        
        private void OnServiceExecuteQueryOperationCompleted(object arg) {
            if ((this.ServiceExecuteQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceExecuteQueryCompleted(this, new ServiceExecuteQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/ServiceExecuteCommand", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ServiceExecuteCommand(string pLoginName, string pLoginPass, string pSqlCommand, string pDatabase) {
            object[] results = this.Invoke("ServiceExecuteCommand", new object[] {
                        pLoginName,
                        pLoginPass,
                        pSqlCommand,
                        pDatabase});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ServiceExecuteCommandAsync(string pLoginName, string pLoginPass, string pSqlCommand, string pDatabase) {
            this.ServiceExecuteCommandAsync(pLoginName, pLoginPass, pSqlCommand, pDatabase, null);
        }
        
        /// <remarks/>
        public void ServiceExecuteCommandAsync(string pLoginName, string pLoginPass, string pSqlCommand, string pDatabase, object userState) {
            if ((this.ServiceExecuteCommandOperationCompleted == null)) {
                this.ServiceExecuteCommandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceExecuteCommandOperationCompleted);
            }
            this.InvokeAsync("ServiceExecuteCommand", new object[] {
                        pLoginName,
                        pLoginPass,
                        pSqlCommand,
                        pDatabase}, this.ServiceExecuteCommandOperationCompleted, userState);
        }
        
        private void OnServiceExecuteCommandOperationCompleted(object arg) {
            if ((this.ServiceExecuteCommandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceExecuteCommandCompleted(this, new ServiceExecuteCommandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/ServiceExecuteCommandByParam", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ServiceExecuteCommandByParam(string pLoginName, string pLoginPass, string pProjectID, string pAccountID, string pFormName, string pFunctionName, string pFunctionType, string pContent, string pCommandType, System.Data.DataTable pCommandParam, string pDevice, string pTag) {
            object[] results = this.Invoke("ServiceExecuteCommandByParam", new object[] {
                        pLoginName,
                        pLoginPass,
                        pProjectID,
                        pAccountID,
                        pFormName,
                        pFunctionName,
                        pFunctionType,
                        pContent,
                        pCommandType,
                        pCommandParam,
                        pDevice,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ServiceExecuteCommandByParamAsync(string pLoginName, string pLoginPass, string pProjectID, string pAccountID, string pFormName, string pFunctionName, string pFunctionType, string pContent, string pCommandType, System.Data.DataTable pCommandParam, string pDevice, string pTag) {
            this.ServiceExecuteCommandByParamAsync(pLoginName, pLoginPass, pProjectID, pAccountID, pFormName, pFunctionName, pFunctionType, pContent, pCommandType, pCommandParam, pDevice, pTag, null);
        }
        
        /// <remarks/>
        public void ServiceExecuteCommandByParamAsync(string pLoginName, string pLoginPass, string pProjectID, string pAccountID, string pFormName, string pFunctionName, string pFunctionType, string pContent, string pCommandType, System.Data.DataTable pCommandParam, string pDevice, string pTag, object userState) {
            if ((this.ServiceExecuteCommandByParamOperationCompleted == null)) {
                this.ServiceExecuteCommandByParamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceExecuteCommandByParamOperationCompleted);
            }
            this.InvokeAsync("ServiceExecuteCommandByParam", new object[] {
                        pLoginName,
                        pLoginPass,
                        pProjectID,
                        pAccountID,
                        pFormName,
                        pFunctionName,
                        pFunctionType,
                        pContent,
                        pCommandType,
                        pCommandParam,
                        pDevice,
                        pTag}, this.ServiceExecuteCommandByParamOperationCompleted, userState);
        }
        
        private void OnServiceExecuteCommandByParamOperationCompleted(object arg) {
            if ((this.ServiceExecuteCommandByParamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceExecuteCommandByParamCompleted(this, new ServiceExecuteCommandByParamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AppStarting", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] CSKH_AppStarting(string pProjectID, string pAccessID, string pAccessKey, string pDeviceID, string pDeviceNM, string pTag) {
            object[] results = this.Invoke("CSKH_AppStarting", new object[] {
                        pProjectID,
                        pAccessID,
                        pAccessKey,
                        pDeviceID,
                        pDeviceNM,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AppStartingAsync(string pProjectID, string pAccessID, string pAccessKey, string pDeviceID, string pDeviceNM, string pTag) {
            this.CSKH_AppStartingAsync(pProjectID, pAccessID, pAccessKey, pDeviceID, pDeviceNM, pTag, null);
        }
        
        /// <remarks/>
        public void CSKH_AppStartingAsync(string pProjectID, string pAccessID, string pAccessKey, string pDeviceID, string pDeviceNM, string pTag, object userState) {
            if ((this.CSKH_AppStartingOperationCompleted == null)) {
                this.CSKH_AppStartingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AppStartingOperationCompleted);
            }
            this.InvokeAsync("CSKH_AppStarting", new object[] {
                        pProjectID,
                        pAccessID,
                        pAccessKey,
                        pDeviceID,
                        pDeviceNM,
                        pTag}, this.CSKH_AppStartingOperationCompleted, userState);
        }
        
        private void OnCSKH_AppStartingOperationCompleted(object arg) {
            if ((this.CSKH_AppStartingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AppStartingCompleted(this, new CSKH_AppStartingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AccountLogin", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CSKH_AccountLogin(string pProjectID, string pAccessID, string pAccessKey, string pAccountID, string pAccountKey, string pDeviceID, string pDeviceNM, string pTag) {
            object[] results = this.Invoke("CSKH_AccountLogin", new object[] {
                        pProjectID,
                        pAccessID,
                        pAccessKey,
                        pAccountID,
                        pAccountKey,
                        pDeviceID,
                        pDeviceNM,
                        pTag});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AccountLoginAsync(string pProjectID, string pAccessID, string pAccessKey, string pAccountID, string pAccountKey, string pDeviceID, string pDeviceNM, string pTag) {
            this.CSKH_AccountLoginAsync(pProjectID, pAccessID, pAccessKey, pAccountID, pAccountKey, pDeviceID, pDeviceNM, pTag, null);
        }
        
        /// <remarks/>
        public void CSKH_AccountLoginAsync(string pProjectID, string pAccessID, string pAccessKey, string pAccountID, string pAccountKey, string pDeviceID, string pDeviceNM, string pTag, object userState) {
            if ((this.CSKH_AccountLoginOperationCompleted == null)) {
                this.CSKH_AccountLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AccountLoginOperationCompleted);
            }
            this.InvokeAsync("CSKH_AccountLogin", new object[] {
                        pProjectID,
                        pAccessID,
                        pAccessKey,
                        pAccountID,
                        pAccountKey,
                        pDeviceID,
                        pDeviceNM,
                        pTag}, this.CSKH_AccountLoginOperationCompleted, userState);
        }
        
        private void OnCSKH_AccountLoginOperationCompleted(object arg) {
            if ((this.CSKH_AccountLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AccountLoginCompleted(this, new CSKH_AccountLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AccountChecking", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CSKH_AccountChecking(string pAccessID, string pAccessKey, string pDeviceID) {
            object[] results = this.Invoke("CSKH_AccountChecking", new object[] {
                        pAccessID,
                        pAccessKey,
                        pDeviceID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AccountCheckingAsync(string pAccessID, string pAccessKey, string pDeviceID) {
            this.CSKH_AccountCheckingAsync(pAccessID, pAccessKey, pDeviceID, null);
        }
        
        /// <remarks/>
        public void CSKH_AccountCheckingAsync(string pAccessID, string pAccessKey, string pDeviceID, object userState) {
            if ((this.CSKH_AccountCheckingOperationCompleted == null)) {
                this.CSKH_AccountCheckingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AccountCheckingOperationCompleted);
            }
            this.InvokeAsync("CSKH_AccountChecking", new object[] {
                        pAccessID,
                        pAccessKey,
                        pDeviceID}, this.CSKH_AccountCheckingOperationCompleted, userState);
        }
        
        private void OnCSKH_AccountCheckingOperationCompleted(object arg) {
            if ((this.CSKH_AccountCheckingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AccountCheckingCompleted(this, new CSKH_AccountCheckingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AccountNew", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] CSKH_AccountNew(string pAccessID, string pAccessKey, string pProjectID, string pSoDanhBo, string pDienThoai, string pEmail, string pPassword, string pDeviceID, string pDeviceNM, string pAppName) {
            object[] results = this.Invoke("CSKH_AccountNew", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pSoDanhBo,
                        pDienThoai,
                        pEmail,
                        pPassword,
                        pDeviceID,
                        pDeviceNM,
                        pAppName});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AccountNewAsync(string pAccessID, string pAccessKey, string pProjectID, string pSoDanhBo, string pDienThoai, string pEmail, string pPassword, string pDeviceID, string pDeviceNM, string pAppName) {
            this.CSKH_AccountNewAsync(pAccessID, pAccessKey, pProjectID, pSoDanhBo, pDienThoai, pEmail, pPassword, pDeviceID, pDeviceNM, pAppName, null);
        }
        
        /// <remarks/>
        public void CSKH_AccountNewAsync(string pAccessID, string pAccessKey, string pProjectID, string pSoDanhBo, string pDienThoai, string pEmail, string pPassword, string pDeviceID, string pDeviceNM, string pAppName, object userState) {
            if ((this.CSKH_AccountNewOperationCompleted == null)) {
                this.CSKH_AccountNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AccountNewOperationCompleted);
            }
            this.InvokeAsync("CSKH_AccountNew", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pSoDanhBo,
                        pDienThoai,
                        pEmail,
                        pPassword,
                        pDeviceID,
                        pDeviceNM,
                        pAppName}, this.CSKH_AccountNewOperationCompleted, userState);
        }
        
        private void OnCSKH_AccountNewOperationCompleted(object arg) {
            if ((this.CSKH_AccountNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AccountNewCompleted(this, new CSKH_AccountNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AccountNew_2", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] CSKH_AccountNew_2(string pAccessID, string pAccessKey, string pProjectID, string pSoDanhBo, string pDienThoai, string pEmail, string pPassword, string pDeviceID, string pDeviceNM, string pAppName, string pAccessID2, string pDeviceID2, string pTag) {
            object[] results = this.Invoke("CSKH_AccountNew_2", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pSoDanhBo,
                        pDienThoai,
                        pEmail,
                        pPassword,
                        pDeviceID,
                        pDeviceNM,
                        pAppName,
                        pAccessID2,
                        pDeviceID2,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AccountNew_2Async(string pAccessID, string pAccessKey, string pProjectID, string pSoDanhBo, string pDienThoai, string pEmail, string pPassword, string pDeviceID, string pDeviceNM, string pAppName, string pAccessID2, string pDeviceID2, string pTag) {
            this.CSKH_AccountNew_2Async(pAccessID, pAccessKey, pProjectID, pSoDanhBo, pDienThoai, pEmail, pPassword, pDeviceID, pDeviceNM, pAppName, pAccessID2, pDeviceID2, pTag, null);
        }
        
        /// <remarks/>
        public void CSKH_AccountNew_2Async(string pAccessID, string pAccessKey, string pProjectID, string pSoDanhBo, string pDienThoai, string pEmail, string pPassword, string pDeviceID, string pDeviceNM, string pAppName, string pAccessID2, string pDeviceID2, string pTag, object userState) {
            if ((this.CSKH_AccountNew_2OperationCompleted == null)) {
                this.CSKH_AccountNew_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AccountNew_2OperationCompleted);
            }
            this.InvokeAsync("CSKH_AccountNew_2", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pSoDanhBo,
                        pDienThoai,
                        pEmail,
                        pPassword,
                        pDeviceID,
                        pDeviceNM,
                        pAppName,
                        pAccessID2,
                        pDeviceID2,
                        pTag}, this.CSKH_AccountNew_2OperationCompleted, userState);
        }
        
        private void OnCSKH_AccountNew_2OperationCompleted(object arg) {
            if ((this.CSKH_AccountNew_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AccountNew_2Completed(this, new CSKH_AccountNew_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AccountUpdate", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] CSKH_AccountUpdate(string pAccessID, string pAccessKey, string pProjectID, string pAccID, string pUpdateType, string[] pData, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] pAvatar, string pDeviceID, string pTag) {
            object[] results = this.Invoke("CSKH_AccountUpdate", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAccID,
                        pUpdateType,
                        pData,
                        pAvatar,
                        pDeviceID,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AccountUpdateAsync(string pAccessID, string pAccessKey, string pProjectID, string pAccID, string pUpdateType, string[] pData, byte[] pAvatar, string pDeviceID, string pTag) {
            this.CSKH_AccountUpdateAsync(pAccessID, pAccessKey, pProjectID, pAccID, pUpdateType, pData, pAvatar, pDeviceID, pTag, null);
        }
        
        /// <remarks/>
        public void CSKH_AccountUpdateAsync(string pAccessID, string pAccessKey, string pProjectID, string pAccID, string pUpdateType, string[] pData, byte[] pAvatar, string pDeviceID, string pTag, object userState) {
            if ((this.CSKH_AccountUpdateOperationCompleted == null)) {
                this.CSKH_AccountUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AccountUpdateOperationCompleted);
            }
            this.InvokeAsync("CSKH_AccountUpdate", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAccID,
                        pUpdateType,
                        pData,
                        pAvatar,
                        pDeviceID,
                        pTag}, this.CSKH_AccountUpdateOperationCompleted, userState);
        }
        
        private void OnCSKH_AccountUpdateOperationCompleted(object arg) {
            if ((this.CSKH_AccountUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AccountUpdateCompleted(this, new CSKH_AccountUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/ServiceOTP_Send", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ServiceOTP_Send(string pAccessID, string pAccessKey, string pProjectID, string pAppID, string pAppUser, string pOTPType, string pOTPPhone, string pDeviceID, string pDeviceNM, string pTag) {
            object[] results = this.Invoke("ServiceOTP_Send", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppID,
                        pAppUser,
                        pOTPType,
                        pOTPPhone,
                        pDeviceID,
                        pDeviceNM,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ServiceOTP_SendAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppID, string pAppUser, string pOTPType, string pOTPPhone, string pDeviceID, string pDeviceNM, string pTag) {
            this.ServiceOTP_SendAsync(pAccessID, pAccessKey, pProjectID, pAppID, pAppUser, pOTPType, pOTPPhone, pDeviceID, pDeviceNM, pTag, null);
        }
        
        /// <remarks/>
        public void ServiceOTP_SendAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppID, string pAppUser, string pOTPType, string pOTPPhone, string pDeviceID, string pDeviceNM, string pTag, object userState) {
            if ((this.ServiceOTP_SendOperationCompleted == null)) {
                this.ServiceOTP_SendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceOTP_SendOperationCompleted);
            }
            this.InvokeAsync("ServiceOTP_Send", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppID,
                        pAppUser,
                        pOTPType,
                        pOTPPhone,
                        pDeviceID,
                        pDeviceNM,
                        pTag}, this.ServiceOTP_SendOperationCompleted, userState);
        }
        
        private void OnServiceOTP_SendOperationCompleted(object arg) {
            if ((this.ServiceOTP_SendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceOTP_SendCompleted(this, new ServiceOTP_SendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/ServiceOTP_Authen", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ServiceOTP_Authen(string pAccessID, string pAccessKey, string pProjectID, string pAppID, string pOTPKey, string pOTPNumber, string pDeviceID, string pTag) {
            object[] results = this.Invoke("ServiceOTP_Authen", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppID,
                        pOTPKey,
                        pOTPNumber,
                        pDeviceID,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ServiceOTP_AuthenAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppID, string pOTPKey, string pOTPNumber, string pDeviceID, string pTag) {
            this.ServiceOTP_AuthenAsync(pAccessID, pAccessKey, pProjectID, pAppID, pOTPKey, pOTPNumber, pDeviceID, pTag, null);
        }
        
        /// <remarks/>
        public void ServiceOTP_AuthenAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppID, string pOTPKey, string pOTPNumber, string pDeviceID, string pTag, object userState) {
            if ((this.ServiceOTP_AuthenOperationCompleted == null)) {
                this.ServiceOTP_AuthenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceOTP_AuthenOperationCompleted);
            }
            this.InvokeAsync("ServiceOTP_Authen", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppID,
                        pOTPKey,
                        pOTPNumber,
                        pDeviceID,
                        pTag}, this.ServiceOTP_AuthenOperationCompleted, userState);
        }
        
        private void OnServiceOTP_AuthenOperationCompleted(object arg) {
            if ((this.ServiceOTP_AuthenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceOTP_AuthenCompleted(this, new ServiceOTP_AuthenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/ServiceOTP_SendTest", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ServiceOTP_SendTest(string pAccessID, string pAccessKey, string pAppID, string pType, string pPhone, string pContent, string pDeviceID, string pTag) {
            object[] results = this.Invoke("ServiceOTP_SendTest", new object[] {
                        pAccessID,
                        pAccessKey,
                        pAppID,
                        pType,
                        pPhone,
                        pContent,
                        pDeviceID,
                        pTag});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ServiceOTP_SendTestAsync(string pAccessID, string pAccessKey, string pAppID, string pType, string pPhone, string pContent, string pDeviceID, string pTag) {
            this.ServiceOTP_SendTestAsync(pAccessID, pAccessKey, pAppID, pType, pPhone, pContent, pDeviceID, pTag, null);
        }
        
        /// <remarks/>
        public void ServiceOTP_SendTestAsync(string pAccessID, string pAccessKey, string pAppID, string pType, string pPhone, string pContent, string pDeviceID, string pTag, object userState) {
            if ((this.ServiceOTP_SendTestOperationCompleted == null)) {
                this.ServiceOTP_SendTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceOTP_SendTestOperationCompleted);
            }
            this.InvokeAsync("ServiceOTP_SendTest", new object[] {
                        pAccessID,
                        pAccessKey,
                        pAppID,
                        pType,
                        pPhone,
                        pContent,
                        pDeviceID,
                        pTag}, this.ServiceOTP_SendTestOperationCompleted, userState);
        }
        
        private void OnServiceOTP_SendTestOperationCompleted(object arg) {
            if ((this.ServiceOTP_SendTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceOTP_SendTestCompleted(this, new ServiceOTP_SendTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AccountLostPass", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CSKH_AccountLostPass(string pAccessID, string pAccessKey, string pProjectID, string pAppName, string pAccID, string pPhone, string pDeviceID, string pTag) {
            object[] results = this.Invoke("CSKH_AccountLostPass", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppName,
                        pAccID,
                        pPhone,
                        pDeviceID,
                        pTag});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AccountLostPassAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppName, string pAccID, string pPhone, string pDeviceID, string pTag) {
            this.CSKH_AccountLostPassAsync(pAccessID, pAccessKey, pProjectID, pAppName, pAccID, pPhone, pDeviceID, pTag, null);
        }
        
        /// <remarks/>
        public void CSKH_AccountLostPassAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppName, string pAccID, string pPhone, string pDeviceID, string pTag, object userState) {
            if ((this.CSKH_AccountLostPassOperationCompleted == null)) {
                this.CSKH_AccountLostPassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AccountLostPassOperationCompleted);
            }
            this.InvokeAsync("CSKH_AccountLostPass", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppName,
                        pAccID,
                        pPhone,
                        pDeviceID,
                        pTag}, this.CSKH_AccountLostPassOperationCompleted, userState);
        }
        
        private void OnCSKH_AccountLostPassOperationCompleted(object arg) {
            if ((this.CSKH_AccountLostPassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AccountLostPassCompleted(this, new CSKH_AccountLostPassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_AccountLostPassUpdate", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CSKH_AccountLostPassUpdate(string pAccessID, string pAccessKey, string pProjectID, string pAppName, string pAccID, string pToken, string pDeviceID, string pTag) {
            object[] results = this.Invoke("CSKH_AccountLostPassUpdate", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppName,
                        pAccID,
                        pToken,
                        pDeviceID,
                        pTag});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_AccountLostPassUpdateAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppName, string pAccID, string pToken, string pDeviceID, string pTag) {
            this.CSKH_AccountLostPassUpdateAsync(pAccessID, pAccessKey, pProjectID, pAppName, pAccID, pToken, pDeviceID, pTag, null);
        }
        
        /// <remarks/>
        public void CSKH_AccountLostPassUpdateAsync(string pAccessID, string pAccessKey, string pProjectID, string pAppName, string pAccID, string pToken, string pDeviceID, string pTag, object userState) {
            if ((this.CSKH_AccountLostPassUpdateOperationCompleted == null)) {
                this.CSKH_AccountLostPassUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_AccountLostPassUpdateOperationCompleted);
            }
            this.InvokeAsync("CSKH_AccountLostPassUpdate", new object[] {
                        pAccessID,
                        pAccessKey,
                        pProjectID,
                        pAppName,
                        pAccID,
                        pToken,
                        pDeviceID,
                        pTag}, this.CSKH_AccountLostPassUpdateOperationCompleted, userState);
        }
        
        private void OnCSKH_AccountLostPassUpdateOperationCompleted(object arg) {
            if ((this.CSKH_AccountLostPassUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_AccountLostPassUpdateCompleted(this, new CSKH_AccountLostPassUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TDService/CSKH_SendSMS", RequestNamespace="http://TDService/", ResponseNamespace="http://TDService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CSKH_SendSMS(string pServiceID, string pServiceKey, string pProjectID, string pAppName, string pAccID, string pSMSType, string[] pPhone, string[] pData, string pSMSContent, string pDeviceID, string pTag) {
            object[] results = this.Invoke("CSKH_SendSMS", new object[] {
                        pServiceID,
                        pServiceKey,
                        pProjectID,
                        pAppName,
                        pAccID,
                        pSMSType,
                        pPhone,
                        pData,
                        pSMSContent,
                        pDeviceID,
                        pTag});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CSKH_SendSMSAsync(string pServiceID, string pServiceKey, string pProjectID, string pAppName, string pAccID, string pSMSType, string[] pPhone, string[] pData, string pSMSContent, string pDeviceID, string pTag) {
            this.CSKH_SendSMSAsync(pServiceID, pServiceKey, pProjectID, pAppName, pAccID, pSMSType, pPhone, pData, pSMSContent, pDeviceID, pTag, null);
        }
        
        /// <remarks/>
        public void CSKH_SendSMSAsync(string pServiceID, string pServiceKey, string pProjectID, string pAppName, string pAccID, string pSMSType, string[] pPhone, string[] pData, string pSMSContent, string pDeviceID, string pTag, object userState) {
            if ((this.CSKH_SendSMSOperationCompleted == null)) {
                this.CSKH_SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSKH_SendSMSOperationCompleted);
            }
            this.InvokeAsync("CSKH_SendSMS", new object[] {
                        pServiceID,
                        pServiceKey,
                        pProjectID,
                        pAppName,
                        pAccID,
                        pSMSType,
                        pPhone,
                        pData,
                        pSMSContent,
                        pDeviceID,
                        pTag}, this.CSKH_SendSMSOperationCompleted, userState);
        }
        
        private void OnCSKH_SendSMSOperationCompleted(object arg) {
            if ((this.CSKH_SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSKH_SendSMSCompleted(this, new CSKH_SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AccountLoginCompletedEventHandler(object sender, AccountLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AccountRegisterCompletedEventHandler(object sender, AccountRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AccountUpdateCompletedEventHandler(object sender, AccountUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AccountChangeCompletedEventHandler(object sender, AccountChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AccountUpdate_PassCompletedEventHandler(object sender, AccountUpdate_PassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountUpdate_PassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountUpdate_PassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ServiceExecuteQueryCompletedEventHandler(object sender, ServiceExecuteQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceExecuteQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceExecuteQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ServiceExecuteCommandCompletedEventHandler(object sender, ServiceExecuteCommandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceExecuteCommandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceExecuteCommandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ServiceExecuteCommandByParamCompletedEventHandler(object sender, ServiceExecuteCommandByParamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceExecuteCommandByParamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceExecuteCommandByParamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AppStartingCompletedEventHandler(object sender, CSKH_AppStartingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AppStartingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AppStartingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AccountLoginCompletedEventHandler(object sender, CSKH_AccountLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AccountLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AccountLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AccountCheckingCompletedEventHandler(object sender, CSKH_AccountCheckingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AccountCheckingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AccountCheckingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AccountNewCompletedEventHandler(object sender, CSKH_AccountNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AccountNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AccountNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AccountNew_2CompletedEventHandler(object sender, CSKH_AccountNew_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AccountNew_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AccountNew_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AccountUpdateCompletedEventHandler(object sender, CSKH_AccountUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AccountUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AccountUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ServiceOTP_SendCompletedEventHandler(object sender, ServiceOTP_SendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceOTP_SendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceOTP_SendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ServiceOTP_AuthenCompletedEventHandler(object sender, ServiceOTP_AuthenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceOTP_AuthenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceOTP_AuthenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ServiceOTP_SendTestCompletedEventHandler(object sender, ServiceOTP_SendTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceOTP_SendTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceOTP_SendTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AccountLostPassCompletedEventHandler(object sender, CSKH_AccountLostPassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AccountLostPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AccountLostPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_AccountLostPassUpdateCompletedEventHandler(object sender, CSKH_AccountLostPassUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_AccountLostPassUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_AccountLostPassUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CSKH_SendSMSCompletedEventHandler(object sender, CSKH_SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CSKH_SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CSKH_SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591